const express = require('express');

// Custom lists (roadmap #7): named, account-scoped collections of titles -
// the tier above the single personal Watchlist (routes/watchlist.js). An admin
// can keep any number ("Halloween Marathon", "Best of 2025", ...), add titles
// from any Discover poster or the MediaDetailModal, and open a list to browse
// its contents through the same modal used everywhere else.
//
// Items live as a stringified JSON array on CustomList.itemsJson (SQLite has no
// Json type - see the schema note), each { id, type, name, poster?, year? }, so
// a list renders without a Cinemeta round-trip per item (same pattern as the
// *WatchHistory / watchlist rows).
module.exports = ({ prisma, getAccountId, decrypt }) => {
  const router = express.Router();

  const parseItems = (raw) => {
    try { const a = JSON.parse(raw || '[]'); return Array.isArray(a) ? a : []; }
    catch { return []; }
  };
  // viewerAccountId is optional - omitted for internal callers that only
  // ever shape a caller's own list (isOwner would always be true there
  // anyway). GET / is the only place that shapes a possibly-not-owned
  // (shared) list, so it's the only caller that needs to pass it.
  const shape = (list, viewerAccountId) => ({
    id: list.id,
    name: list.name,
    description: list.description || null,
    items: parseItems(list.itemsJson),
    coverImageUrl: list.coverImageUrl || null,
    coverColorIndex: list.coverColorIndex ?? null,
    importSourceUrl: list.importSourceUrl || null,
    autoRefresh: !!list.autoRefresh,
    autoRefreshFrequency: list.autoRefreshFrequency === 'weekly' ? 'weekly' : 'daily',
    lastAutoRefreshAt: list.lastAutoRefreshAt || null,
    pinned: !!list.pinned,
    shared: !!list.shared,
    // Whether this catalog is published to OTHER instances - a boolean only,
    // never the token. GET / can return catalogs owned by a different account
    // on this instance (shared:true), and the token is the share URL's
    // credential; it is readable only via GET /:id/federation, which is
    // ownership-scoped.
    federationPublished: !!list.federationToken,
    autoGenerated: !!list.autoGenerated,
    keptRatings: require('../utils/contentRating').parseKeptRatings(list.keptRatings),
    lastRemovalAt: list.lastRemovalAt || null,
    isOwner: viewerAccountId === undefined ? true : list.accountId === viewerAccountId,
    createdAt: list.createdAt,
    updatedAt: list.updatedAt,
  });
  // Normalize an incoming item to the stored shape; null if it's not usable.
  const normalizeItem = (body) => {
    const id = body?.id || body?.itemId;
    const type = body?.type || body?.itemType;
    const name = body?.name;
    if (!id || !name) return null;
    if (type !== 'movie' && type !== 'series') return null;
    return { id: String(id), type, name: String(name), poster: body.poster || null, year: body.year || null };
  };

  // GET /api/lists — this account's own lists, newest-updated first, plus
  // any OTHER account's catalogs shared with the whole instance (shared:
  // true). Merged into one response (own lists first) so every existing
  // client caller - which finds a list by id out of this same array - keeps
  // working unchanged for a shared catalog's detail page too, with no
  // separate fetch path to wire up.
  router.get('/', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const [ownLists, sharedLists] = await Promise.all([
        prisma.customList.findMany({ where: { accountId }, orderBy: { updatedAt: 'desc' } }),
        prisma.customList.findMany({ where: { shared: true, accountId: { not: accountId } }, orderBy: { updatedAt: 'desc' } }),
      ]);
      res.json([
        ...ownLists.map((l) => shape(l, accountId)),
        ...sharedLists.map((l) => shape(l, accountId)),
      ]);
    } catch (e) {
      console.error('Error fetching custom lists:', e);
      res.status(500).json({ error: 'Failed to fetch lists' });
    }
  });

  // POST /api/lists — create a list. { name, description? }
  router.post('/', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const name = (req.body?.name || '').trim();
      if (!name) return res.status(400).json({ error: 'name is required' });
      const list = await prisma.customList.create({
        data: { accountId, name, description: (req.body?.description || '').trim() || null, itemsJson: '[]' },
      });
      res.status(201).json(shape(list));
    } catch (e) {
      console.error('Error creating custom list:', e);
      res.status(500).json({ error: 'Failed to create list' });
    }
  });

  // POST /api/lists/describe-preview — "A 90s neo-noir under two hours nobody
  // here has seen" -> a real preview of catalog items, nothing saved yet. See
  // server/utils/nlCatalog.js for the two-stage pipeline (description ->
  // structured query -> TMDb Discover, always excluding the household's own
  // watch history). `query`/`usedAi` are returned alongside the items so the
  // client can show "here's what I understood" before the admin commits to
  // saving it - an AI (or even the keyword fallback) can misread a request,
  // and silently saving a catalog that doesn't match what was asked for would
  // be worse than a wrong search result, which is at least visibly wrong.
  router.post('/describe-preview', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const description = String(req.body?.description || '');
      const { generateCatalogFromDescription } = require('../utils/nlCatalog');
      const result = await generateCatalogFromDescription(prisma, accountId, decrypt, description);
      res.json(result);
    } catch (e) {
      console.error('Error previewing described catalog:', e);
      res.status(400).json({ error: e.message || 'Failed to generate a preview' });
    }
  });

  // POST /api/lists/from-description — saves a catalog from a prior preview.
  // Takes the items the client already fetched via describe-preview rather
  // than re-running the pipeline (a second TMDb round-trip could return
  // slightly different results and would just be wasted work - the admin
  // already saw and approved these exact items).
  router.post('/from-description', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const name = (req.body?.name || '').trim();
      const description = String(req.body?.description || '').trim();
      if (!name) return res.status(400).json({ error: 'name is required' });
      const items = Array.isArray(req.body?.items) ? req.body.items.map(normalizeItem).filter(Boolean) : [];
      const list = await prisma.customList.create({
        data: { accountId, name, description: description || null, itemsJson: JSON.stringify(items) },
      });
      res.status(201).json(shape(list));
    } catch (e) {
      console.error('Error saving described catalog:', e);
      res.status(500).json({ error: 'Failed to save catalog' });
    }
  });

  // POST /api/lists/import — create a list from a pasted TMDb or MDBList URL.
  // { url, name? } - name overrides the source list's own name if given.
  // Provider is auto-detected from the URL host, so this is the only import
  // entry point (no separate per-provider routes/UI).
  router.post('/import', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const url = String(req.body?.url || '').trim();
      if (!url) return res.status(400).json({ error: 'url is required' });

      const { detectProvider, importFromTmdb, importFromMdblist, importFromTrakt, importFromSlickSync, importFromAniList, importFromMyAnimeList, resolveTmdbKey, resolveMdblistKey, resolveKeyFromSettings } = require('../utils/listImport');
      const provider = detectProvider(url);
      if (!provider) {
        return res.status(400).json({ error: 'Unrecognized list URL - paste a TMDb (themoviedb.org/list/...), MDBList (mdblist.com/lists/...), Trakt (trakt.tv/users/.../lists/...), AniList (anilist.co/user/NAME/animelist) or MyAnimeList (myanimelist.net/animelist/NAME) URL, or a SlickSync catalog share link' });
      }

      let result;
      if (provider === 'slicksync') {
        // Subscribing to another household's catalog. Nothing else here
        // changes: it is stored with importSourceUrl set like any imported
        // catalog, so "Refresh from source", the diff, autoRefresh and the
        // daily worker all apply to it unmodified.
        result = await importFromSlickSync(url);
      } else if (provider === 'tmdb') {
        const key = await resolveTmdbKey(prisma, getAccountId, req);
        result = await importFromTmdb(key, url);
      } else if (provider === 'anilist' || provider === 'myanimelist') {
        // Anime lists resolve through TMDb, since neither source carries
        // IMDb ids and every other part of the app is tt-based.
        const key = await resolveTmdbKey(prisma, getAccountId, req);
        if (provider === 'anilist') {
          result = await importFromAniList(url, key);
        } else {
          // MAL needs a client id of its own; AniList needs nothing.
          const malClientId = await resolveKeyFromSettings(prisma, getAccountId, req, 'malClientId', 'MAL_CLIENT_ID', { allowBackup: false });
          result = await importFromMyAnimeList(url, key, malClientId);
        }
      } else if (provider === 'trakt') {
        // Public lists only, and only a client id - see importFromTrakt.
        const clientId = await resolveKeyFromSettings(prisma, getAccountId, req, 'traktClientId', 'TRAKT_CLIENT_ID', { allowBackup: false });
        result = await importFromTrakt(url, clientId);
      } else {
        const key = await resolveMdblistKey(prisma, getAccountId, req);
        result = await importFromMdblist(key, url);
      }

      if (result.items.length === 0) {
        return res.status(422).json({ error: 'That list has no importable titles (or none could be resolved to an IMDb id)' });
      }

      const name = (req.body?.name || '').trim() || result.name;
      const list = await prisma.customList.create({
        data: { accountId, name, itemsJson: JSON.stringify(result.items), importSourceUrl: url },
      });
      res.status(201).json({ ...shape(list), truncated: !!result.truncated, totalAvailable: result.totalAvailable });
    } catch (e) {
      console.error('Error importing list:', e);
      res.status(400).json({ error: e?.message || 'Failed to import list' });
    }
  });

  // POST /api/lists/:id/refresh — re-pull this catalog's own
  // importSourceUrl and replace its items with the source's current
  // contents. { apply?: boolean } - without apply, only returns the diff
  // (added/removed/unchanged counts) so the client can show a confirm step
  // before committing; wholesale replace is destructive to any titles
  // added/removed by hand since the original import, so this is never a
  // silent operation.
  // --- Smart Catalogs (utils/smartCatalogs.js) ---
  //
  // A catalog that keeps its CRITERIA instead of a fixed list, re-evaluated
  // on the same auto-refresh tick URL-imported catalogs already use.
  router.put('/:id/smart-rule', async (req, res) => {
    try {
      const accountId = getAccountId(req)
      const list = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } })
      if (!list) return res.status(404).json({ error: 'Catalog not found' })
      const { normalizeRule, describeRule } = require('../utils/smartCatalogs')
      // An explicit null clears the rule and the catalog goes back to being
      // an ordinary hand-built one, keeping whatever items it has.
      if (req.body?.rule === null) {
        await prisma.customList.update({ where: { id: list.id }, data: { smartRuleJson: null } })
        return res.json({ success: true, rule: null, description: '' })
      }
      const rule = normalizeRule(req.body?.rule)
      await prisma.customList.update({
        where: { id: list.id },
        data: { smartRuleJson: JSON.stringify(rule), autoRefresh: req.body?.autoRefresh !== false },
      })
      res.json({ success: true, rule, description: describeRule(rule) })
    } catch (e) {
      res.status(500).json({ error: e?.message || 'Failed to save the rule' })
    }
  })

  // Evaluate now, without waiting for the daily tick.
  router.post('/:id/smart-refresh', async (req, res) => {
    try {
      const accountId = getAccountId(req)
      const list = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } })
      if (!list) return res.status(404).json({ error: 'Catalog not found' })
      if (!list.smartRuleJson) return res.status(400).json({ error: 'This catalog has no rule - set one first' })
      const { refreshSmartCatalog } = require('../utils/smartCatalogs')
      const { resolveTmdbKeyForAccount } = require('../utils/listImport')
      const tmdbKey = await resolveTmdbKeyForAccount(prisma, accountId)
      if (!tmdbKey) return res.status(400).json({ error: 'A TMDb key is needed to evaluate a rule (Settings -> External API Keys)' })
      const result = await refreshSmartCatalog(prisma, accountId, list, tmdbKey)
      if (!result) return res.status(502).json({ error: 'Could not evaluate the rule just now - the catalog was left as it was' })
      res.json({ success: true, ...result })
    } catch (e) {
      res.status(500).json({ error: e?.message || 'Refresh failed' })
    }
  })

  router.post('/:id/refresh', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });

      const { refreshListFromSourceForAccount } = require('../utils/listImport');
      const { items, added, removed, unchanged } = await refreshListFromSourceForAccount(prisma, accountId, existing);

      if (req.body?.apply) {
        const list = await prisma.customList.update({ where: { id: existing.id }, data: { itemsJson: JSON.stringify(items) } });
        return res.json({ ...shape(list), added, removed, unchanged });
      }
      res.json({ ...shape(existing), added, removed, unchanged, applied: false });
    } catch (e) {
      console.error('Error refreshing list:', e);
      res.status(400).json({ error: e?.message || 'Failed to refresh list from source' });
    }
  });

  // PATCH /api/lists/:id — rename / re-describe / set cover art.
  // { name?, description?, coverImageUrl?, coverColorIndex? } - cover fields
  // accept `null` explicitly to clear back to the auto-collage fallback.
  router.patch('/:id', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const body = req.body || {};
      const data = {};
      if (typeof body.name === 'string' && body.name.trim()) data.name = body.name.trim();
      if (typeof body.description === 'string') data.description = body.description.trim() || null;
      if ('coverImageUrl' in body) data.coverImageUrl = body.coverImageUrl ? String(body.coverImageUrl) : null;
      if ('coverColorIndex' in body) data.coverColorIndex = body.coverColorIndex === null || body.coverColorIndex === undefined ? null : Number(body.coverColorIndex);
      if ('pinned' in body) data.pinned = !!body.pinned;
      if ('autoRefresh' in body) {
        if (body.autoRefresh && !existing.importSourceUrl) {
          return res.status(400).json({ error: 'This catalog wasn\'t imported from a list, so there\'s no source to auto-refresh from.' });
        }
        data.autoRefresh = !!body.autoRefresh;
      }
      if ('autoRefreshFrequency' in body) {
        data.autoRefreshFrequency = body.autoRefreshFrequency === 'weekly' ? 'weekly' : 'daily';
      }
      if ('shared' in body) data.shared = !!body.shared;
      // keptRatings is deliberately NOT settable here - it's now a
      // destructive allowlist (applying it removes items), not a passive
      // flag list, so it only changes via POST /:id/apply-content-rating,
      // which sets it and performs the removal as one atomic step. A plain
      // PATCH silently changing what will be removed the next time someone
      // applies it, with no preview, is exactly the surprise this whole
      // rework exists to prevent.
      const list = await prisma.customList.update({ where: { id: existing.id }, data });
      res.json(shape(list));
    } catch (e) {
      console.error('Error updating custom list:', e);
      res.status(500).json({ error: 'Failed to update list' });
    }
  });

  // DELETE /api/lists/:id — remove the whole list.
  // Read back the current share URL without rotating it. Separate from the
  // POST below on purpose: re-opening the share dialog must not invalidate a
  // link the owner has already handed to somebody.
  router.get('/:id/federation', async (req, res) => {
    try {
      const accountId = getAccountId(req);
      const list = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!list) return res.status(404).json({ error: 'List not found' });
      if (!list.federationToken) return res.json({ published: false });
      res.json({
        published: true,
        federationToken: list.federationToken,
        path: `/api/federation/catalog/${list.id}?key=${list.federationToken}`,
      });
    } catch (error) {
      console.error('Failed to read catalog share link:', error?.message);
      res.status(500).json({ error: 'Failed to read share link' });
    }
  });

  // --- Federation: publish / rotate / revoke ---------------------------------
  //
  // Publishing is per-catalog and opt-in, and separate from `shared` (which
  // means "other accounts on THIS instance"). The token lives in the share
  // URL, so it is shown in full on mint and readable afterwards by the owner -
  // it protects a curated title list, not a credential, and an owner who
  // cannot re-read their own share URL would just delete and re-publish.
  //
  // POST mints or rotates: calling it again on an already-published catalog
  // issues a new token and immediately invalidates the previous URL.
  router.post('/:id/federation', async (req, res) => {
    try {
      const accountId = getAccountId(req);
      const list = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!list) return res.status(404).json({ error: 'List not found' });

      // 32 bytes of CSPRNG, url-safe. Long enough that the endpoint's
      // deliberate 404-on-everything gives an attacker nothing to work with.
      const token = require('crypto').randomBytes(32).toString('base64url');
      await prisma.customList.update({ where: { id: list.id }, data: { federationToken: token } });

      res.json({
        federationToken: token,
        rotated: Boolean(list.federationToken),
        // Path only. The publisher's externally reachable origin is not
        // reliably knowable from in here (reverse proxies, custom domains),
        // so the client joins this onto its own origin and the owner can
        // correct it if the instance is reached by another hostname.
        path: `/api/federation/catalog/${list.id}?key=${token}`,
      });
    } catch (error) {
      console.error('Failed to publish catalog:', error?.message);
      res.status(500).json({ error: 'Failed to publish catalog' });
    }
  });

  // Revoke. Any instance already subscribed keeps whatever items it last
  // pulled - this stops future pulls, it does not reach into a subscriber and
  // delete their copy.
  router.delete('/:id/federation', async (req, res) => {
    try {
      const accountId = getAccountId(req);
      const list = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!list) return res.status(404).json({ error: 'List not found' });
      await prisma.customList.update({ where: { id: list.id }, data: { federationToken: null } });
      res.json({ ok: true });
    } catch (error) {
      console.error('Failed to unpublish catalog:', error?.message);
      res.status(500).json({ error: 'Failed to unpublish catalog' });
    }
  });

  router.delete('/:id', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      // Archived to Trash before deletion so an accidental delete is one
      // click to undo - see utils/trash.js. The archive is written first; if
      // it fails, nothing is deleted and we fall back to a plain delete
      // rather than refusing the request.
      let trashId = null;
      try {
        const { archiveAndDelete } = require('../utils/trash');
        trashId = (await archiveAndDelete(prisma, accountId, 'catalog', existing.id)).id;
      } catch (e) {
        console.error('[Trash] Archive failed, deleting without undo:', e?.message);
        await prisma.customList.delete({ where: { id: existing.id } });
      }
      // A deleted auto-generated catalog must never come back on the next
      // scan just because the same taste cluster is still detected - see
      // autoThemedCatalogs.js's own comment for why this mirrors the
      // duplicate-account merge suggestions' dismiss-persists-forever design.
      if (existing.autoGenerated && existing.autoGeneratedKey) {
        try {
          await prisma.dismissedThemedCatalog.upsert({
            where: { accountId_key: { accountId, key: existing.autoGeneratedKey } },
            update: {},
            create: { accountId, key: existing.autoGeneratedKey },
          });
        } catch (e) {
          console.warn('Failed to record themed-catalog dismissal:', e?.message);
        }
      }
      res.json({ success: true, trashId });
    } catch (e) {
      console.error('Error deleting custom list:', e);
      res.status(500).json({ error: 'Failed to delete list' });
    }
  });

  // POST /api/lists/:id/items — add a title. De-duped by item id (re-adding a
  // title already in the list is a no-op rather than a duplicate row).
  router.post('/:id/items', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const item = normalizeItem(req.body || {});
      if (!item) return res.status(400).json({ error: 'id, name, and a valid type are required' });

      // Content-rating allowlist gate - the single choke point every "Add to
      // catalog" UI action funnels through, so this is enough to cover all
      // of them without duplicating the check at each call site. An unknown
      // rating (no OMDb data, or OMDb not configured) is never blocked here
      // either - same "never auto-reject/remove on missing data" rule
      // apply-content-rating already follows.
      const { parseKeptRatings, isKept } = require('../utils/contentRating');
      const keptRatings = parseKeptRatings(existing.keptRatings);
      if (keptRatings.length > 0 && item.id && item.id.startsWith('tt')) {
        const { resolveOmdbKey } = require('../utils/listImport');
        const { fetchOmdbRatings } = require('../utils/omdb');
        const apiKey = await resolveOmdbKey(prisma, getAccountId, req);
        if (apiKey) {
          const ratings = await fetchOmdbRatings(item.id, apiKey).catch(() => null);
          if (ratings?.rated && !isKept(ratings.rated, keptRatings)) {
            return res.status(403).json({
              error: `"${item.name}" is rated ${ratings.rated}, which isn't in this catalog's content rating policy (${keptRatings.join(', ')}). Change the policy to allow it, or add it to a different catalog.`,
            });
          }
        }
      }

      const items = parseItems(existing.itemsJson);
      if (!items.some((i) => i.id === item.id)) items.push(item);
      const list = await prisma.customList.update({
        where: { id: existing.id },
        data: { itemsJson: JSON.stringify(items) },
      });
      res.json(shape(list));
    } catch (e) {
      console.error('Error adding item to custom list:', e);
      res.status(500).json({ error: 'Failed to add item' });
    }
  });

  // POST /api/lists/:id/items/bulk — add many titles in one write. Exists
  // for share-code imports (client/lib/shareCodes.ts): a 200-title catalog
  // as 200 sequential single-item POSTs is 200 round trips and 200 JSON
  // rewrites of the same blob. Same normalizeItem validation per item and
  // same de-dupe as the single route; the content-rating allowlist gate is
  // NOT applied here on purpose - it needs one OMDb request per title, and
  // a bulk import into a rating-gated catalog is instead handled the same
  // way URL imports already are (the gate applies to later hand-adds).
  router.post('/:id/items/bulk', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const raw = Array.isArray(req.body?.items) ? req.body.items : null;
      if (!raw || raw.length === 0) return res.status(400).json({ error: 'items array is required' });
      if (raw.length > 2000) return res.status(400).json({ error: 'Too many items (max 2000)' });

      const incoming = raw.map((r) => normalizeItem(r || {})).filter(Boolean);
      if (incoming.length === 0) return res.status(400).json({ error: 'No valid items - each needs id, name, and a valid type' });

      const items = parseItems(existing.itemsJson);
      const have = new Set(items.map((i) => i.id));
      let added = 0;
      for (const item of incoming) {
        if (have.has(item.id)) continue;
        have.add(item.id);
        items.push(item);
        added += 1;
      }
      const list = await prisma.customList.update({
        where: { id: existing.id },
        data: { itemsJson: JSON.stringify(items) },
      });
      res.json({ ...shape(list), added });
    } catch (e) {
      console.error('Error bulk-adding items to custom list:', e);
      res.status(500).json({ error: 'Failed to add items' });
    }
  });

  // DELETE /api/lists/:id/items/:itemId — remove a title from the list.
  router.delete('/:id/items/:itemId', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const items = parseItems(existing.itemsJson).filter((i) => i.id !== req.params.itemId);
      const list = await prisma.customList.update({
        where: { id: existing.id },
        data: { itemsJson: JSON.stringify(items) },
      });
      res.json(shape(list));
    } catch (e) {
      console.error('Error removing item from custom list:', e);
      res.status(500).json({ error: 'Failed to remove item' });
    }
  });

  // PATCH /api/lists/:id/items/reorder — persist a manual drag-reorder.
  // { orderedIds: string[] } must contain EXACTLY the list's current item
  // ids (same set, any order) - rejected otherwise, since itemsJson is one
  // opaque JSON blob with no relational position column to reconcile a
  // partial/stale reorder against (e.g. a client that missed a concurrent
  // add/remove in another tab).
  router.patch('/:id/items/reorder', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const orderedIds = Array.isArray(req.body?.orderedIds) ? req.body.orderedIds.map(String) : null;
      if (!orderedIds) return res.status(400).json({ error: 'orderedIds must be an array' });

      const items = parseItems(existing.itemsJson);
      const currentIds = new Set(items.map((i) => i.id));
      const sameSet = orderedIds.length === items.length
        && new Set(orderedIds).size === items.length
        && orderedIds.every((id) => currentIds.has(id));
      if (!sameSet) {
        return res.status(400).json({ error: 'orderedIds must match the list\'s current items exactly (it may have changed since you loaded it)' });
      }

      const byId = new Map(items.map((i) => [i.id, i]));
      const reordered = orderedIds.map((id) => byId.get(id));
      const list = await prisma.customList.update({
        where: { id: existing.id },
        data: { itemsJson: JSON.stringify(reordered) },
      });
      res.json(shape(list));
    } catch (e) {
      console.error('Error reordering custom list items:', e);
      res.status(500).json({ error: 'Failed to reorder items' });
    }
  });

  // GET /api/lists/:id/suggest?query= — propose titles for this catalog by
  // theme (TMDb keyword search, seeded from the catalog's own name unless
  // ?query= overrides it). Read-only: returns candidates for the caller to
  // review and add one-by-one via the existing POST .../items - nothing is
  // ever added automatically by this endpoint itself.
  router.get('/:id/suggest', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });

      const { suggestTitlesForCatalog, resolveTmdbKey } = require('../utils/listImport');
      const key = await resolveTmdbKey(prisma, getAccountId, req);
      const query = (typeof req.query.query === 'string' && req.query.query.trim()) ? req.query.query.trim() : existing.name;
      const existingIds = parseItems(existing.itemsJson).map((i) => i.id);
      const suggestions = await suggestTitlesForCatalog(key, query, existingIds);
      res.json({ suggestions, query });
    } catch (e) {
      console.error('Error suggesting catalog titles:', e);
      res.status(400).json({ error: e?.message || 'Failed to suggest titles' });
    }
  });

  // Shared by preview/apply below - fetches OMDb ratings for every item and
  // splits them into keep/remove/unknown against a CANDIDATE ratings list
  // (not necessarily the catalog's currently-saved one - preview needs to
  // show the effect of whatever's checked in the UI right now, before
  // anything is saved).
  async function computeContentRatingSplit(req, items, candidateKeptRatings) {
    const { isKept } = require('../utils/contentRating');
    if (!candidateKeptRatings || candidateKeptRatings.length === 0 || items.length === 0) {
      return { keep: items, remove: [], unknown: [] }
    }
    const { resolveOmdbKey, mapLimit } = require('../utils/listImport');
    const { fetchOmdbRatings } = require('../utils/omdb');
    const apiKey = await resolveOmdbKey(prisma, getAccountId, req);
    if (!apiKey) {
      const err = new Error('OMDb API key not configured (Settings -> External API Keys) - required to check content ratings');
      err.status = 400;
      throw err;
    }
    const results = await mapLimit(items, 8, async (item) => {
      if (!item.id || !item.id.startsWith('tt')) return { item, rated: null };
      const ratings = await fetchOmdbRatings(item.id, apiKey).catch(() => null);
      return { item, rated: ratings?.rated || null };
    });
    const keep = [];
    const remove = [];
    const unknown = [];
    for (const r of results) {
      if (!r.rated) unknown.push(r.item);
      if (isKept(r.rated, candidateKeptRatings)) keep.push({ ...r.item, rated: r.rated });
      else remove.push({ ...r.item, rated: r.rated });
    }
    return { keep, remove, unknown };
  }

  // GET /api/lists/:id/content-rating-breakdown — what's actually in this
  // catalog RIGHT NOW, by rating, independent of any candidate policy - so
  // the Content Rating modal can show "this catalog currently has 3 PG-13,
  // 2 R, 5 unrated" before anyone checks a single box, instead of that only
  // becoming visible after picking ratings and hitting Preview.
  router.get('/:id/content-rating-breakdown', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });

      const items = parseItems(existing.itemsJson);
      if (items.length === 0) return res.json({ counts: {}, unknownCount: 0, checked: 0 });

      const { resolveOmdbKey, mapLimit } = require('../utils/listImport');
      const { fetchOmdbRatings } = require('../utils/omdb');
      const apiKey = await resolveOmdbKey(prisma, getAccountId, req);
      if (!apiKey) {
        return res.status(400).json({ error: 'OMDb API key not configured (Settings -> External API Keys) - required to check content ratings' });
      }

      const results = await mapLimit(items, 8, async (item) => {
        if (!item.id || !item.id.startsWith('tt')) return null;
        const ratings = await fetchOmdbRatings(item.id, apiKey).catch(() => null);
        return ratings?.rated || null;
      });

      const counts = {};
      let unknownCount = 0;
      for (const rated of results) {
        if (!rated) { unknownCount++; continue; }
        counts[rated] = (counts[rated] || 0) + 1;
      }
      res.json({ counts, unknownCount, checked: items.length });
    } catch (e) {
      console.error('Error computing content rating breakdown:', e);
      res.status(400).json({ error: e?.message || 'Failed to compute content rating breakdown' });
    }
  });

  // GET /api/lists/:id/preview-content-rating?keep=G,PG — shows what a
  // candidate allowlist would do to this catalog's CURRENT items, without
  // changing anything. Run this before /apply-content-rating, not after -
  // once applied, removed items are only recoverable via
  // /restore-content-rating, and only for the single most recent removal.
  router.get('/:id/preview-content-rating', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });

      const candidateKeptRatings = String(req.query?.keep || '').split(',').map((r) => r.trim()).filter(Boolean);
      const items = parseItems(existing.itemsJson);
      const { keep, remove, unknown } = await computeContentRatingSplit(req, items, candidateKeptRatings);
      res.json({ keep, remove, unknown, checked: items.length });
    } catch (e) {
      console.error('Error previewing catalog content rating:', e);
      res.status(e?.status || 400).json({ error: e?.message || 'Failed to preview content rating' });
    }
  });

  // POST /api/lists/:id/apply-content-rating — { keptRatings: string[] }.
  // Actually removes every current item whose OMDb rating isn't in
  // keptRatings (unknown-rating items are never removed by this - see
  // contentRating.js's isKept comment), saves the new policy, and snapshots
  // the pre-removal itemsJson into lastRemovalSnapshot so
  // /restore-content-rating can undo it. keptRatings: [] clears the policy
  // without removing anything (an empty allowlist would otherwise mean
  // "keep nothing," which is never what clearing the policy should do).
  router.post('/:id/apply-content-rating', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });

      const { serializeKeptRatings } = require('../utils/contentRating');
      const keptRatingsInput = Array.isArray(req.body?.keptRatings) ? req.body.keptRatings.filter((r) => typeof r === 'string') : [];
      const items = parseItems(existing.itemsJson);

      if (keptRatingsInput.length === 0) {
        const list = await prisma.customList.update({
          where: { id: existing.id },
          data: { keptRatings: null },
        });
        return res.json({ ...shape(list), removedCount: 0 });
      }

      const { remove } = await computeContentRatingSplit(req, items, keptRatingsInput);
      const removeIds = new Set(remove.map((r) => r.id));
      const keptItems = items.filter((it) => !removeIds.has(it.id));

      const list = await prisma.customList.update({
        where: { id: existing.id },
        data: {
          keptRatings: serializeKeptRatings(keptRatingsInput),
          itemsJson: JSON.stringify(keptItems),
          // Snapshot BEFORE this removal, not the removed items themselves -
          // restoring is "put itemsJson back," which also correctly
          // recovers anything added/removed by hand between preview and
          // apply, not just what this specific removal touched.
          lastRemovalSnapshot: remove.length > 0 ? existing.itemsJson : existing.lastRemovalSnapshot,
          lastRemovalAt: remove.length > 0 ? new Date() : existing.lastRemovalAt,
        },
      });
      res.json({ ...shape(list), removedCount: remove.length });
    } catch (e) {
      console.error('Error applying catalog content rating:', e);
      res.status(e?.status || 400).json({ error: e?.message || 'Failed to apply content rating' });
    }
  });

  // POST /api/lists/:id/restore-content-rating — undoes the single most
  // recent /apply-content-rating removal: restores itemsJson from
  // lastRemovalSnapshot AND clears keptRatings back to no-policy. Both
  // together, not just the items - apply set them as one atomic action
  // (the policy and the removal it caused), so undo reverses both halves.
  // Leaving keptRatings set after a restore would show the Content Rating
  // button as still "active" for a policy whose actual effect had just
  // been undone. One-step undo, not a history stack - there is nothing to
  // restore once this has been called, or once a later removal has
  // overwritten the snapshot.
  router.post('/:id/restore-content-rating', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      if (!existing.lastRemovalSnapshot) return res.status(400).json({ error: 'Nothing to restore' });

      const list = await prisma.customList.update({
        where: { id: existing.id },
        data: { itemsJson: existing.lastRemovalSnapshot, lastRemovalSnapshot: null, lastRemovalAt: null, keptRatings: null },
      });
      res.json(shape(list));
    } catch (e) {
      console.error('Error restoring catalog content rating removal:', e);
      res.status(500).json({ error: 'Failed to restore' });
    }
  });

  // GET /api/lists/simkl-users — managed users in this account who've linked
  // a personal SIMKL account (Users page > user detail > "Link SIMKL"), for
  // the Import-from-SIMKL / Export-to-SIMKL user picker. SIMKL has no named
  // Custom Lists API (see server/utils/simklLists.js) so both flows act on a
  // specific user's Plan to Watch, not an account-wide list - hence the
  // picker instead of a single implicit source.
  router.get('/simkl-users', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const users = await prisma.user.findMany({
        where: { accountId, simklAccessToken: { not: null } },
        select: { id: true, username: true, avatarUrl: true, colorIndex: true },
        orderBy: { username: 'asc' },
      });
      res.json(users);
    } catch (e) {
      console.error('Error listing SIMKL-linked users:', e);
      res.status(500).json({ error: 'Failed to list SIMKL-linked users' });
    }
  });

  // GET /api/lists/simkl-discover?list=trending|anticipated&type=movies|shows
  // — Discover row backing SIMKL's public feeds. Account-wide (needs only a
  // SIMKL Client ID, no linked user) - see fetchSimklDiscoverRow's own
  // comment for why these specific endpoints don't need a per-user token.
  router.get('/simkl-discover', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const list = String(req.query?.list || 'trending');
      const mediaType = String(req.query?.type || 'movies');
      const { fetchSimklDiscoverRow } = require('../utils/simklLists');
      const items = await fetchSimklDiscoverRow(prisma, accountId, { list, mediaType });
      res.json({ items });
    } catch (e) {
      console.error('Error fetching SIMKL discover row:', e);
      res.status(400).json({ error: e?.message || 'Failed to fetch SIMKL discover row' });
    }
  });

  // POST /api/lists/import-simkl — create a catalog from a linked user's
  // SIMKL Plan to Watch. { userId, name? }
  router.post('/import-simkl', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const userId = String(req.body?.userId || '').trim();
      if (!userId) return res.status(400).json({ error: 'userId is required' });
      const linkedUser = await prisma.user.findFirst({ where: { id: userId, accountId } });
      if (!linkedUser) return res.status(404).json({ error: 'User not found' });

      const { importSimklWatchlist } = require('../utils/simklLists');
      const result = await importSimklWatchlist(prisma, linkedUser);
      if (result.items.length === 0) {
        return res.status(422).json({ error: `${linkedUser.username}'s SIMKL Plan to Watch is empty (or none of it resolved to an IMDb id)` });
      }

      const name = (req.body?.name || '').trim() || result.name;
      const list = await prisma.customList.create({
        data: { accountId, name, itemsJson: JSON.stringify(result.items) },
      });
      res.status(201).json({ ...shape(list), totalAvailable: result.totalAvailable });
    } catch (e) {
      console.error('Error importing SIMKL Plan to Watch:', e);
      res.status(400).json({ error: e?.message || 'Failed to import from SIMKL' });
    }
  });

  // POST /api/lists/:id/export-simkl — add this catalog's items to a linked
  // user's SIMKL Plan to Watch. { userId }
  router.post('/:id/export-simkl', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const items = parseItems(existing.itemsJson);
      if (items.length === 0) return res.status(422).json({ error: 'This catalog has no titles to export' });

      const userId = String(req.body?.userId || '').trim();
      if (!userId) return res.status(400).json({ error: 'userId is required' });
      const linkedUser = await prisma.user.findFirst({ where: { id: userId, accountId } });
      if (!linkedUser) return res.status(404).json({ error: 'User not found' });

      const { exportListToSimklWatchlist } = require('../utils/simklLists');
      const result = await exportListToSimklWatchlist(prisma, linkedUser, items);
      res.json({ ...result, username: linkedUser.username });
    } catch (e) {
      console.error('Error exporting list to SIMKL:', e);
      res.status(400).json({ error: e?.message || 'Failed to export to SIMKL' });
    }
  });

  // POST /api/lists/:id/export-mdblist — create a brand-new MDBList list
  // from this catalog's current items. One-way: this app can create the
  // list, but wiring it into a Stremio/Nuvio addon (e.g. AIOMetadata) as a
  // catalog source is a manual step in that addon's own config afterward.
  router.post('/:id/export-mdblist', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const items = parseItems(existing.itemsJson);
      if (items.length === 0) return res.status(422).json({ error: 'This catalog has no titles to export' });

      const { exportListToMdblist, resolveMdblistKey } = require('../utils/listImport');
      const key = await resolveMdblistKey(prisma, getAccountId, req);
      const result = await exportListToMdblist(key, existing.name, items);
      res.json(result);
    } catch (e) {
      console.error('Error exporting list to MDBList:', e);
      res.status(400).json({ error: e?.message || 'Failed to export to MDBList' });
    }
  });

  return router;
};
