const express = require('express');

// Custom lists (roadmap #7): named, account-scoped collections of titles -
// the tier above the single personal Watchlist (routes/watchlist.js). An admin
// can keep any number ("Halloween Marathon", "Best of 2025", ...), add titles
// from any Discover poster or the MediaDetailModal, and open a list to browse
// its contents through the same modal used everywhere else.
//
// Items live as a stringified JSON array on CustomList.itemsJson (SQLite has no
// Json type - see the schema note), each { id, type, name, poster?, year? }, so
// a list renders without a Cinemeta round-trip per item (same pattern as the
// *WatchHistory / watchlist rows).
module.exports = ({ prisma, getAccountId, decrypt }) => {
  const router = express.Router();

  const parseItems = (raw) => {
    try { const a = JSON.parse(raw || '[]'); return Array.isArray(a) ? a : []; }
    catch { return []; }
  };
  // viewerAccountId is optional - omitted for internal callers that only
  // ever shape a caller's own list (isOwner would always be true there
  // anyway). GET / is the only place that shapes a possibly-not-owned
  // (shared) list, so it's the only caller that needs to pass it.
  const shape = (list, viewerAccountId) => ({
    id: list.id,
    name: list.name,
    description: list.description || null,
    items: parseItems(list.itemsJson),
    coverImageUrl: list.coverImageUrl || null,
    coverColorIndex: list.coverColorIndex ?? null,
    importSourceUrl: list.importSourceUrl || null,
    autoRefresh: !!list.autoRefresh,
    autoRefreshFrequency: list.autoRefreshFrequency === 'weekly' ? 'weekly' : 'daily',
    lastAutoRefreshAt: list.lastAutoRefreshAt || null,
    pinned: !!list.pinned,
    shared: !!list.shared,
    autoGenerated: !!list.autoGenerated,
    blockedRatings: require('../utils/contentRating').parseBlockedRatings(list.blockedRatings),
    isOwner: viewerAccountId === undefined ? true : list.accountId === viewerAccountId,
    createdAt: list.createdAt,
    updatedAt: list.updatedAt,
  });
  // Normalize an incoming item to the stored shape; null if it's not usable.
  const normalizeItem = (body) => {
    const id = body?.id || body?.itemId;
    const type = body?.type || body?.itemType;
    const name = body?.name;
    if (!id || !name) return null;
    if (type !== 'movie' && type !== 'series') return null;
    return { id: String(id), type, name: String(name), poster: body.poster || null, year: body.year || null };
  };

  // GET /api/lists — this account's own lists, newest-updated first, plus
  // any OTHER account's catalogs shared with the whole instance (shared:
  // true). Merged into one response (own lists first) so every existing
  // client caller - which finds a list by id out of this same array - keeps
  // working unchanged for a shared catalog's detail page too, with no
  // separate fetch path to wire up.
  router.get('/', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const [ownLists, sharedLists] = await Promise.all([
        prisma.customList.findMany({ where: { accountId }, orderBy: { updatedAt: 'desc' } }),
        prisma.customList.findMany({ where: { shared: true, accountId: { not: accountId } }, orderBy: { updatedAt: 'desc' } }),
      ]);
      res.json([
        ...ownLists.map((l) => shape(l, accountId)),
        ...sharedLists.map((l) => shape(l, accountId)),
      ]);
    } catch (e) {
      console.error('Error fetching custom lists:', e);
      res.status(500).json({ error: 'Failed to fetch lists' });
    }
  });

  // POST /api/lists — create a list. { name, description? }
  router.post('/', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const name = (req.body?.name || '').trim();
      if (!name) return res.status(400).json({ error: 'name is required' });
      const list = await prisma.customList.create({
        data: { accountId, name, description: (req.body?.description || '').trim() || null, itemsJson: '[]' },
      });
      res.status(201).json(shape(list));
    } catch (e) {
      console.error('Error creating custom list:', e);
      res.status(500).json({ error: 'Failed to create list' });
    }
  });

  // POST /api/lists/describe-preview — "A 90s neo-noir under two hours nobody
  // here has seen" -> a real preview of catalog items, nothing saved yet. See
  // server/utils/nlCatalog.js for the two-stage pipeline (description ->
  // structured query -> TMDb Discover, always excluding the household's own
  // watch history). `query`/`usedAi` are returned alongside the items so the
  // client can show "here's what I understood" before the admin commits to
  // saving it - an AI (or even the keyword fallback) can misread a request,
  // and silently saving a catalog that doesn't match what was asked for would
  // be worse than a wrong search result, which is at least visibly wrong.
  router.post('/describe-preview', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const description = String(req.body?.description || '');
      const { generateCatalogFromDescription } = require('../utils/nlCatalog');
      const result = await generateCatalogFromDescription(prisma, accountId, decrypt, description);
      res.json(result);
    } catch (e) {
      console.error('Error previewing described catalog:', e);
      res.status(400).json({ error: e.message || 'Failed to generate a preview' });
    }
  });

  // POST /api/lists/from-description — saves a catalog from a prior preview.
  // Takes the items the client already fetched via describe-preview rather
  // than re-running the pipeline (a second TMDb round-trip could return
  // slightly different results and would just be wasted work - the admin
  // already saw and approved these exact items).
  router.post('/from-description', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const name = (req.body?.name || '').trim();
      const description = String(req.body?.description || '').trim();
      if (!name) return res.status(400).json({ error: 'name is required' });
      const items = Array.isArray(req.body?.items) ? req.body.items.map(normalizeItem).filter(Boolean) : [];
      const list = await prisma.customList.create({
        data: { accountId, name, description: description || null, itemsJson: JSON.stringify(items) },
      });
      res.status(201).json(shape(list));
    } catch (e) {
      console.error('Error saving described catalog:', e);
      res.status(500).json({ error: 'Failed to save catalog' });
    }
  });

  // POST /api/lists/import — create a list from a pasted TMDb or MDBList URL.
  // { url, name? } - name overrides the source list's own name if given.
  // Provider is auto-detected from the URL host, so this is the only import
  // entry point (no separate per-provider routes/UI).
  router.post('/import', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const url = String(req.body?.url || '').trim();
      if (!url) return res.status(400).json({ error: 'url is required' });

      const { detectProvider, importFromTmdb, importFromMdblist, resolveTmdbKey, resolveMdblistKey } = require('../utils/listImport');
      const provider = detectProvider(url);
      if (!provider) {
        return res.status(400).json({ error: 'Unrecognized list URL - paste a TMDb (themoviedb.org/list/...) or MDBList (mdblist.com/lists/...) list URL' });
      }

      let result;
      if (provider === 'tmdb') {
        const key = await resolveTmdbKey(prisma, getAccountId, req);
        result = await importFromTmdb(key, url);
      } else {
        const key = await resolveMdblistKey(prisma, getAccountId, req);
        result = await importFromMdblist(key, url);
      }

      if (result.items.length === 0) {
        return res.status(422).json({ error: 'That list has no importable titles (or none could be resolved to an IMDb id)' });
      }

      const name = (req.body?.name || '').trim() || result.name;
      const list = await prisma.customList.create({
        data: { accountId, name, itemsJson: JSON.stringify(result.items), importSourceUrl: url },
      });
      res.status(201).json({ ...shape(list), truncated: !!result.truncated, totalAvailable: result.totalAvailable });
    } catch (e) {
      console.error('Error importing list:', e);
      res.status(400).json({ error: e?.message || 'Failed to import list' });
    }
  });

  // POST /api/lists/:id/refresh — re-pull this catalog's own
  // importSourceUrl and replace its items with the source's current
  // contents. { apply?: boolean } - without apply, only returns the diff
  // (added/removed/unchanged counts) so the client can show a confirm step
  // before committing; wholesale replace is destructive to any titles
  // added/removed by hand since the original import, so this is never a
  // silent operation.
  router.post('/:id/refresh', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });

      const { refreshListFromSourceForAccount } = require('../utils/listImport');
      const { items, added, removed, unchanged } = await refreshListFromSourceForAccount(prisma, accountId, existing);

      if (req.body?.apply) {
        const list = await prisma.customList.update({ where: { id: existing.id }, data: { itemsJson: JSON.stringify(items) } });
        return res.json({ ...shape(list), added, removed, unchanged });
      }
      res.json({ ...shape(existing), added, removed, unchanged, applied: false });
    } catch (e) {
      console.error('Error refreshing list:', e);
      res.status(400).json({ error: e?.message || 'Failed to refresh list from source' });
    }
  });

  // PATCH /api/lists/:id — rename / re-describe / set cover art.
  // { name?, description?, coverImageUrl?, coverColorIndex? } - cover fields
  // accept `null` explicitly to clear back to the auto-collage fallback.
  router.patch('/:id', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const body = req.body || {};
      const data = {};
      if (typeof body.name === 'string' && body.name.trim()) data.name = body.name.trim();
      if (typeof body.description === 'string') data.description = body.description.trim() || null;
      if ('coverImageUrl' in body) data.coverImageUrl = body.coverImageUrl ? String(body.coverImageUrl) : null;
      if ('coverColorIndex' in body) data.coverColorIndex = body.coverColorIndex === null || body.coverColorIndex === undefined ? null : Number(body.coverColorIndex);
      if ('pinned' in body) data.pinned = !!body.pinned;
      if ('autoRefresh' in body) {
        if (body.autoRefresh && !existing.importSourceUrl) {
          return res.status(400).json({ error: 'This catalog wasn\'t imported from a list, so there\'s no source to auto-refresh from.' });
        }
        data.autoRefresh = !!body.autoRefresh;
      }
      if ('autoRefreshFrequency' in body) {
        data.autoRefreshFrequency = body.autoRefreshFrequency === 'weekly' ? 'weekly' : 'daily';
      }
      if ('shared' in body) data.shared = !!body.shared;
      if ('blockedRatings' in body) {
        data.blockedRatings = require('../utils/contentRating').serializeBlockedRatings(body.blockedRatings);
      }
      const list = await prisma.customList.update({ where: { id: existing.id }, data });
      res.json(shape(list));
    } catch (e) {
      console.error('Error updating custom list:', e);
      res.status(500).json({ error: 'Failed to update list' });
    }
  });

  // DELETE /api/lists/:id — remove the whole list.
  router.delete('/:id', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      await prisma.customList.delete({ where: { id: existing.id } });
      // A deleted auto-generated catalog must never come back on the next
      // scan just because the same taste cluster is still detected - see
      // autoThemedCatalogs.js's own comment for why this mirrors the
      // duplicate-account merge suggestions' dismiss-persists-forever design.
      if (existing.autoGenerated && existing.autoGeneratedKey) {
        try {
          await prisma.dismissedThemedCatalog.upsert({
            where: { accountId_key: { accountId, key: existing.autoGeneratedKey } },
            update: {},
            create: { accountId, key: existing.autoGeneratedKey },
          });
        } catch (e) {
          console.warn('Failed to record themed-catalog dismissal:', e?.message);
        }
      }
      res.json({ success: true });
    } catch (e) {
      console.error('Error deleting custom list:', e);
      res.status(500).json({ error: 'Failed to delete list' });
    }
  });

  // POST /api/lists/:id/items — add a title. De-duped by item id (re-adding a
  // title already in the list is a no-op rather than a duplicate row).
  router.post('/:id/items', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const item = normalizeItem(req.body || {});
      if (!item) return res.status(400).json({ error: 'id, name, and a valid type are required' });
      const items = parseItems(existing.itemsJson);
      if (!items.some((i) => i.id === item.id)) items.push(item);
      const list = await prisma.customList.update({
        where: { id: existing.id },
        data: { itemsJson: JSON.stringify(items) },
      });
      res.json(shape(list));
    } catch (e) {
      console.error('Error adding item to custom list:', e);
      res.status(500).json({ error: 'Failed to add item' });
    }
  });

  // DELETE /api/lists/:id/items/:itemId — remove a title from the list.
  router.delete('/:id/items/:itemId', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const items = parseItems(existing.itemsJson).filter((i) => i.id !== req.params.itemId);
      const list = await prisma.customList.update({
        where: { id: existing.id },
        data: { itemsJson: JSON.stringify(items) },
      });
      res.json(shape(list));
    } catch (e) {
      console.error('Error removing item from custom list:', e);
      res.status(500).json({ error: 'Failed to remove item' });
    }
  });

  // PATCH /api/lists/:id/items/reorder — persist a manual drag-reorder.
  // { orderedIds: string[] } must contain EXACTLY the list's current item
  // ids (same set, any order) - rejected otherwise, since itemsJson is one
  // opaque JSON blob with no relational position column to reconcile a
  // partial/stale reorder against (e.g. a client that missed a concurrent
  // add/remove in another tab).
  router.patch('/:id/items/reorder', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const orderedIds = Array.isArray(req.body?.orderedIds) ? req.body.orderedIds.map(String) : null;
      if (!orderedIds) return res.status(400).json({ error: 'orderedIds must be an array' });

      const items = parseItems(existing.itemsJson);
      const currentIds = new Set(items.map((i) => i.id));
      const sameSet = orderedIds.length === items.length
        && new Set(orderedIds).size === items.length
        && orderedIds.every((id) => currentIds.has(id));
      if (!sameSet) {
        return res.status(400).json({ error: 'orderedIds must match the list\'s current items exactly (it may have changed since you loaded it)' });
      }

      const byId = new Map(items.map((i) => [i.id, i]));
      const reordered = orderedIds.map((id) => byId.get(id));
      const list = await prisma.customList.update({
        where: { id: existing.id },
        data: { itemsJson: JSON.stringify(reordered) },
      });
      res.json(shape(list));
    } catch (e) {
      console.error('Error reordering custom list items:', e);
      res.status(500).json({ error: 'Failed to reorder items' });
    }
  });

  // GET /api/lists/:id/suggest?query= — propose titles for this catalog by
  // theme (TMDb keyword search, seeded from the catalog's own name unless
  // ?query= overrides it). Read-only: returns candidates for the caller to
  // review and add one-by-one via the existing POST .../items - nothing is
  // ever added automatically by this endpoint itself.
  router.get('/:id/suggest', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });

      const { suggestTitlesForCatalog, resolveTmdbKey } = require('../utils/listImport');
      const key = await resolveTmdbKey(prisma, getAccountId, req);
      const query = (typeof req.query.query === 'string' && req.query.query.trim()) ? req.query.query.trim() : existing.name;
      const existingIds = parseItems(existing.itemsJson).map((i) => i.id);
      const suggestions = await suggestTitlesForCatalog(key, query, existingIds);
      res.json({ suggestions, query });
    } catch (e) {
      console.error('Error suggesting catalog titles:', e);
      res.status(400).json({ error: e?.message || 'Failed to suggest titles' });
    }
  });

  // GET /api/lists/:id/flagged — checks this catalog's CURRENT items against
  // its OWN current blockedRatings policy (server/utils/contentRating.js).
  // A review tool, not a live gate: run it after adding a batch of titles,
  // or after changing the policy, to see what needs a second look. Requires
  // an OMDb key (Settings -> External API Keys) - OMDb is the only source
  // this app has for content/age ratings (distinct from OMDb's other job
  // here, quality scores). Items with no items to check, or no policy set,
  // return an empty flagged list rather than an error.
  router.get('/:id/flagged', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });

      const { parseBlockedRatings, isFlagged } = require('../utils/contentRating');
      const blockedRatings = parseBlockedRatings(existing.blockedRatings);
      const items = parseItems(existing.itemsJson);
      if (blockedRatings.length === 0 || items.length === 0) {
        return res.json({ flagged: [], unknown: [], checked: 0, policy: blockedRatings });
      }

      const { resolveOmdbKey, mapLimit } = require('../utils/listImport');
      const { fetchOmdbRatings } = require('../utils/omdb');
      const apiKey = await resolveOmdbKey(prisma, getAccountId, req);
      if (!apiKey) {
        return res.status(400).json({ error: 'OMDb API key not configured (Settings -> External API Keys) - required to check content ratings' });
      }

      const results = await mapLimit(items, 8, async (item) => {
        if (!item.id || !item.id.startsWith('tt')) return { item, rated: null };
        const ratings = await fetchOmdbRatings(item.id, apiKey).catch(() => null);
        return { item, rated: ratings?.rated || null };
      });

      const flagged = results.filter((r) => isFlagged(r.rated, blockedRatings)).map((r) => ({ ...r.item, rated: r.rated }));
      const unknown = results.filter((r) => !r.rated).map((r) => r.item);

      res.json({ flagged, unknown, checked: items.length, policy: blockedRatings });
    } catch (e) {
      console.error('Error checking catalog content ratings:', e);
      res.status(400).json({ error: e?.message || 'Failed to check content ratings' });
    }
  });

  // GET /api/lists/simkl-users — managed users in this account who've linked
  // a personal SIMKL account (Users page > user detail > "Link SIMKL"), for
  // the Import-from-SIMKL / Export-to-SIMKL user picker. SIMKL has no named
  // Custom Lists API (see server/utils/simklLists.js) so both flows act on a
  // specific user's Plan to Watch, not an account-wide list - hence the
  // picker instead of a single implicit source.
  router.get('/simkl-users', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const users = await prisma.user.findMany({
        where: { accountId, simklAccessToken: { not: null } },
        select: { id: true, username: true, avatarUrl: true, colorIndex: true },
        orderBy: { username: 'asc' },
      });
      res.json(users);
    } catch (e) {
      console.error('Error listing SIMKL-linked users:', e);
      res.status(500).json({ error: 'Failed to list SIMKL-linked users' });
    }
  });

  // GET /api/lists/simkl-discover?list=trending|anticipated&type=movies|shows
  // — Discover row backing SIMKL's public feeds. Account-wide (needs only a
  // SIMKL Client ID, no linked user) - see fetchSimklDiscoverRow's own
  // comment for why these specific endpoints don't need a per-user token.
  router.get('/simkl-discover', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const list = String(req.query?.list || 'trending');
      const mediaType = String(req.query?.type || 'movies');
      const { fetchSimklDiscoverRow } = require('../utils/simklLists');
      const items = await fetchSimklDiscoverRow(prisma, accountId, { list, mediaType });
      res.json({ items });
    } catch (e) {
      console.error('Error fetching SIMKL discover row:', e);
      res.status(400).json({ error: e?.message || 'Failed to fetch SIMKL discover row' });
    }
  });

  // POST /api/lists/import-simkl — create a catalog from a linked user's
  // SIMKL Plan to Watch. { userId, name? }
  router.post('/import-simkl', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const userId = String(req.body?.userId || '').trim();
      if (!userId) return res.status(400).json({ error: 'userId is required' });
      const linkedUser = await prisma.user.findFirst({ where: { id: userId, accountId } });
      if (!linkedUser) return res.status(404).json({ error: 'User not found' });

      const { importSimklWatchlist } = require('../utils/simklLists');
      const result = await importSimklWatchlist(prisma, linkedUser);
      if (result.items.length === 0) {
        return res.status(422).json({ error: `${linkedUser.username}'s SIMKL Plan to Watch is empty (or none of it resolved to an IMDb id)` });
      }

      const name = (req.body?.name || '').trim() || result.name;
      const list = await prisma.customList.create({
        data: { accountId, name, itemsJson: JSON.stringify(result.items) },
      });
      res.status(201).json({ ...shape(list), totalAvailable: result.totalAvailable });
    } catch (e) {
      console.error('Error importing SIMKL Plan to Watch:', e);
      res.status(400).json({ error: e?.message || 'Failed to import from SIMKL' });
    }
  });

  // POST /api/lists/:id/export-simkl — add this catalog's items to a linked
  // user's SIMKL Plan to Watch. { userId }
  router.post('/:id/export-simkl', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const items = parseItems(existing.itemsJson);
      if (items.length === 0) return res.status(422).json({ error: 'This catalog has no titles to export' });

      const userId = String(req.body?.userId || '').trim();
      if (!userId) return res.status(400).json({ error: 'userId is required' });
      const linkedUser = await prisma.user.findFirst({ where: { id: userId, accountId } });
      if (!linkedUser) return res.status(404).json({ error: 'User not found' });

      const { exportListToSimklWatchlist } = require('../utils/simklLists');
      const result = await exportListToSimklWatchlist(prisma, linkedUser, items);
      res.json({ ...result, username: linkedUser.username });
    } catch (e) {
      console.error('Error exporting list to SIMKL:', e);
      res.status(400).json({ error: e?.message || 'Failed to export to SIMKL' });
    }
  });

  // POST /api/lists/:id/export-mdblist — create a brand-new MDBList list
  // from this catalog's current items. One-way: this app can create the
  // list, but wiring it into a Stremio/Nuvio addon (e.g. AIOMetadata) as a
  // catalog source is a manual step in that addon's own config afterward.
  router.post('/:id/export-mdblist', async (req, res) => {
    try {
      const accountId = getAccountId(req) || 'default';
      const existing = await prisma.customList.findFirst({ where: { id: req.params.id, accountId } });
      if (!existing) return res.status(404).json({ error: 'List not found' });
      const items = parseItems(existing.itemsJson);
      if (items.length === 0) return res.status(422).json({ error: 'This catalog has no titles to export' });

      const { exportListToMdblist, resolveMdblistKey } = require('../utils/listImport');
      const key = await resolveMdblistKey(prisma, getAccountId, req);
      const result = await exportListToMdblist(key, existing.name, items);
      res.json(result);
    } catch (e) {
      console.error('Error exporting list to MDBList:', e);
      res.status(400).json({ error: e?.message || 'Failed to export to MDBList' });
    }
  });

  return router;
};
