const express = require('express');
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs')
const { decrypt, encrypt } = require('../utils/encryption')
const { DEFAULT_ACCOUNT_ID, DEFAULT_ACCOUNT_UUID } = require('../utils/config')
const { postDiscord } = require('../utils/notify')
const { DEFAULT_TIMEZONE } = require('../utils/dateUtils')
const { normalizeOmdbApiKey } = require('../utils/omdb')

module.exports = ({ prisma, INSTANCE_TYPE, getAccountDek, getDecryptedManifestUrl, getAccountId }) => {
  const router = express.Router();

  const ensureDefaultAccount = async () => {
    const privatePassword = process.env.PRIVATE_ACCOUNT_PASSWORD || 'private-mode'
    const defaultSyncPayload = JSON.stringify({ enabled: false, frequency: '0', safe: true, mode: 'normal', webhookUrl: null, notifyOnActivity: false, notifyOnSync: false, notifyOnInvite: false })

    let account = await prisma.appAccount.findUnique({ where: { id: DEFAULT_ACCOUNT_ID } })
    if (!account) {
      const passwordHash = await bcrypt.hash(privatePassword, 12)
      account = await prisma.appAccount.create({
        data: {
          id: DEFAULT_ACCOUNT_ID,
          uuid: DEFAULT_ACCOUNT_UUID,
          passwordHash,
          sync: defaultSyncPayload
        }
      })
      return account
    }

    const updates = {}
    if (!account.uuid || account.uuid !== DEFAULT_ACCOUNT_UUID) {
      updates.uuid = DEFAULT_ACCOUNT_UUID
    }
    if (!account.passwordHash) {
      updates.passwordHash = await bcrypt.hash(privatePassword, 12)
    }
    if (!account.sync) {
      updates.sync = defaultSyncPayload
    }

    if (Object.keys(updates).length) {
      account = await prisma.appAccount.update({ where: { id: DEFAULT_ACCOUNT_ID }, data: updates })
    }

    return account
  }

  router.get('/account-info', async (req, res) => {
    try {
      if (INSTANCE_TYPE !== 'public') {
        const account = await ensureDefaultAccount()
        return res.json({
          id: DEFAULT_ACCOUNT_ID,
          uuid: account?.uuid || DEFAULT_ACCOUNT_UUID,
        })
      }

      if (!req.appAccountId) {
        return res.status(401).json({ message: 'Unauthorized' })
      }

      const account = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { id: true, uuid: true } })
      if (!account) {
        return res.status(404).json({ message: 'Account not found' })
      }
      return res.json(account)
    } catch (e) {
      return res.status(500).json({ message: 'Failed to load account info', error: e?.message })
    }
  })

  // PUT /account-avatar - set or clear the admin's own profile picture
  // (full URL or /uploads/avatars/<file> from the shared avatar upload endpoint)
  router.put('/account-avatar', async (req, res) => {
    try {
      const { avatarUrl } = req.body || {}
      const accountId = INSTANCE_TYPE !== 'public' ? (await ensureDefaultAccount()).id : req.appAccountId
      if (!accountId) {
        return res.status(401).json({ message: 'Unauthorized' })
      }
      await prisma.appAccount.update({ where: { id: accountId }, data: { avatarUrl: avatarUrl || null } })
      return res.json({ avatarUrl: avatarUrl || null })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to update avatar', error: e?.message })
    }
  })

  // PUT /account-display-name - self-service nickname, set by the account
  // holder themselves (Settings). Only meaningful in public multi-tenant
  // mode - it's what makes an account recognizable on the superadmin panel
  // instead of by raw UUID, but that panel only ever reads it, never writes.
  router.put('/account-display-name', async (req, res) => {
    try {
      const { displayName } = req.body || {}
      const accountId = INSTANCE_TYPE !== 'public' ? (await ensureDefaultAccount()).id : req.appAccountId
      if (!accountId) {
        return res.status(401).json({ message: 'Unauthorized' })
      }
      const trimmed = displayName === null || displayName === undefined ? null : String(displayName).trim().slice(0, 60) || null
      await prisma.appAccount.update({ where: { id: accountId }, data: { displayName: trimmed } })
      return res.json({ displayName: trimmed })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to update display name', error: e?.message })
    }
  })

  // Backup settings endpoints - only available in private mode
  if (INSTANCE_TYPE !== 'public') {
    // Use centralized backup utilities
    const {
      BACKUP_DIR,
      ensureBackupDir,
      readBackupFrequencyDays,
      writeBackupFrequencyDays,
      performBackupOnce,
      clearBackupSchedule,
      scheduleBackups
    } = require('../utils/backup');

    // Filenames are always generated by performBackupOnce() as
    // config-backup-<ISO-ish timestamp>.json - allow-listing that exact
    // shape (plus a plain path.basename check below) is defense against
    // path traversal via a crafted :filename param, since these three
    // routes read/write/delete files on disk from a URL segment.
    const isValidBackupFilename = (name) =>
      typeof name === 'string' &&
      /^config-backup-[0-9T-]+\.json$/.test(name) &&
      path.basename(name) === name;

    // GET /settings/backups - list backups on disk, newest first. Each
    // entry's `validation` comes from the sidecar file backupValidation.js
    // writes right after the backup itself - absent (not re-computed here)
    // for backups written before that existed.
    router.get('/backups', async (req, res) => {
      try {
        ensureBackupDir()
        const files = fs.readdirSync(BACKUP_DIR).filter(isValidBackupFilename)
        const backups = files.map((filename) => {
          const stat = fs.statSync(path.join(BACKUP_DIR, filename))
          let validation = null
          try {
            const validationFile = path.join(BACKUP_DIR, filename.replace(/\.json$/, '.validation.json'))
            if (fs.existsSync(validationFile)) validation = JSON.parse(fs.readFileSync(validationFile, 'utf8'))
          } catch {}
          return { filename, size: stat.size, createdAt: stat.mtime.toISOString(), validation }
        }).sort((a, b) => b.createdAt.localeCompare(a.createdAt))
        return res.json(backups)
      } catch (e) {
        return res.status(500).json({ message: 'Failed to list backups', error: e?.message })
      }
    })

    // GET /settings/db-size - SQLite file size history for the Tasks page's
    // storage chart. Read-only; { supported: false } in public/Postgres mode.
    router.get('/db-size', async (req, res) => {
      try {
        const { getDbSizeReport } = require('../utils/dbSizeMonitor')
        const report = await getDbSizeReport(prisma, getAccountId(req) || DEFAULT_ACCOUNT_ID)
        return res.json(report)
      } catch (e) {
        return res.status(500).json({ message: 'Failed to get DB size report', error: e?.message })
      }
    })

    // GET /settings/backups/:filename/download - raw backup file
    router.get('/backups/:filename/download', async (req, res) => {
      try {
        if (!isValidBackupFilename(req.params.filename)) {
          return res.status(400).json({ message: 'Invalid backup filename' })
        }
        const filePath = path.join(BACKUP_DIR, req.params.filename)
        if (!fs.existsSync(filePath)) return res.status(404).json({ message: 'Backup not found' })
        return res.download(filePath, req.params.filename)
      } catch (e) {
        return res.status(500).json({ message: 'Failed to download backup', error: e?.message })
      }
    })

    // POST /settings/backups/:filename/restore - DESTRUCTIVE: replaces all
    // current users/groups/addons with the backup's contents. Reads the
    // file server-side and forwards it into the existing, already-battle-
    // tested /public-auth/config-import handler (same internal-fetch
    // pattern performBackupOnce() already uses to call sibling endpoints)
    // rather than duplicating its import-ordering logic here.
    router.post('/backups/:filename/restore', async (req, res) => {
      try {
        if (!isValidBackupFilename(req.params.filename)) {
          return res.status(400).json({ message: 'Invalid backup filename' })
        }
        const filePath = path.join(BACKUP_DIR, req.params.filename)
        if (!fs.existsSync(filePath)) return res.status(404).json({ message: 'Backup not found' })

        const jsonData = fs.readFileSync(filePath, 'utf8')
        const baseUrl = `http://localhost:${process.env.PORT || 4000}`
        const rsp = await fetch(`${baseUrl}/api/public-auth/config-import`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ jsonData }),
        })
        const result = await rsp.json().catch(() => ({}))
        if (!rsp.ok) {
          return res.status(rsp.status).json(result?.message ? result : { message: 'Restore failed' })
        }
        return res.json(result)
      } catch (e) {
        return res.status(500).json({ message: 'Failed to restore backup', error: e?.message })
      }
    })

    // POST /settings/disaster-recovery-kit/export - unlike the regular
    // config backup above (Users/Groups/Addons only), this also bundles
    // every Vault secret, decrypted and re-encrypted under the passphrase
    // supplied here instead of this instance's own ENCRYPTION_KEY - so the
    // resulting file is portable to a brand-new instance if this one and
    // its key are both lost. Manual/on-demand only, never scheduled.
    router.post('/disaster-recovery-kit/export', async (req, res) => {
      try {
        const accountId = getAccountId(req) || 'default'
        const { passphrase } = req.body || {}
        const { buildKit } = require('../utils/disasterRecoveryKit')
        const kit = await buildKit(prisma, accountId, passphrase, req, { decrypt })
        res.setHeader('Content-Disposition', `attachment; filename="slicksync-recovery-kit-${new Date().toISOString().split('T')[0]}.json"`)
        return res.json(kit)
      } catch (e) {
        return res.status(400).json({ message: e?.message || 'Failed to build recovery kit' })
      }
    })

    // POST /settings/disaster-recovery-kit/import - DESTRUCTIVE, same as
    // restore-from-backup (replaces current Users/Groups/Addons), PLUS
    // creates a new Vault entry for every secret in the kit, re-encrypted
    // under THIS instance's own current ENCRYPTION_KEY.
    router.post('/disaster-recovery-kit/import', async (req, res) => {
      try {
        const accountId = getAccountId(req) || 'default'
        const { passphrase, kit } = req.body || {}
        const { restoreKit } = require('../utils/disasterRecoveryKit')
        const result = await restoreKit(prisma, accountId, passphrase, kit, req, { encrypt })
        return res.json(result)
      } catch (e) {
        return res.status(400).json({ message: e?.message || 'Failed to restore recovery kit' })
      }
    })

    // POST /settings/mosaic/generate-now - manual trigger for the monthly
    // poster mosaic, mainly so the feature can be tried/tested without
    // waiting for the scheduler's own month-rollover check. Defaults to the
    // most recently completed month (same target the scheduler picks);
    // optionally accepts { month: "YYYY-MM" } to regenerate/test a specific
    // one. No webhook required - generateAndPostMosaic falls back to a
    // plain push+bell text summary when cfg.webhookUrl is unset.
    router.post('/mosaic/generate-now', async (req, res) => {
      try {
        const accountId = getAccountId(req) || 'default'
        const { getAccountMonthString, previousMonthString, resolveAccountTimezone } = require('../utils/dateUtils')
        const { generateAndPostMosaic } = require('../utils/posterMosaic')

        const acc = await prisma.appAccount.findUnique({ where: { id: accountId }, select: { sync: true } })
        let cfg = acc?.sync
        if (typeof cfg === 'string') { try { cfg = JSON.parse(cfg) } catch { cfg = {} } }
        cfg = cfg || {}

        const timeZone = await resolveAccountTimezone(prisma, accountId)
        const month = (typeof req.body?.month === 'string' && /^\d{4}-\d{2}$/.test(req.body.month))
          ? req.body.month
          : previousMonthString(getAccountMonthString(new Date(), timeZone))

        const result = await generateAndPostMosaic(prisma, accountId, cfg.webhookUrl, month, timeZone)
        return res.json(result)
      } catch (e) {
        return res.status(500).json({ message: e?.message || 'Failed to generate mosaic' })
      }
    })

    // DELETE /settings/backups/:filename
    router.delete('/backups/:filename', async (req, res) => {
      try {
        if (!isValidBackupFilename(req.params.filename)) {
          return res.status(400).json({ message: 'Invalid backup filename' })
        }
        const filePath = path.join(BACKUP_DIR, req.params.filename)
        if (!fs.existsSync(filePath)) return res.status(404).json({ message: 'Backup not found' })
        fs.unlinkSync(filePath)
        try {
          const validationFile = filePath.replace(/\.json$/, '.validation.json')
          if (fs.existsSync(validationFile)) fs.unlinkSync(validationFile)
        } catch {}
        return res.json({ success: true })
      } catch (e) {
        return res.status(500).json({ message: 'Failed to delete backup', error: e?.message })
      }
    })

    let backupTimer = null

    // Initialize backup schedule on startup
    scheduleBackups(readBackupFrequencyDays(), prisma)

    // Get backup frequency setting
    router.get('/backup-frequency', async (req, res) => {
      try {
        return res.json({ days: readBackupFrequencyDays() })
      } catch {
        return res.status(500).json({ message: 'Failed to read backup frequency' })
      }
    })

    // Update backup frequency setting
    router.put('/backup-frequency', async (req, res) => {
      try {
        const days = Number(req.body?.days || 0)
        if (!Number.isFinite(days) || days < 0) return res.status(400).json({ message: 'Invalid days' })
        writeBackupFrequencyDays(days)
        scheduleBackups(days, prisma)
        return res.json({ message: 'Backup frequency updated', days })
      } catch {
        return res.status(500).json({ message: 'Failed to update backup frequency' })
      }
    })

    // Manual backup trigger
    router.post('/backup-now', async (req, res) => {
      try {
        await performBackupOnce(prisma)
        return res.json({ message: 'Backup started' })
      } catch {
        return res.status(500).json({ message: 'Failed to start backup' })
      }
    })
  }

  // Backup frequency endpoints - available in all modes (public returns disabled)
  router.get('/backup-frequency', async (req, res) => {
    try {
      if (INSTANCE_TYPE === 'public') {
        // Backups are not supported in public mode
        return res.json({ days: 0 })
      }
      const { readBackupFrequencyDays } = require('../utils/backup')
      return res.json({ days: readBackupFrequencyDays() })
    } catch {
      return res.status(500).json({ message: 'Failed to read backup frequency' })
    }
  })

  router.put('/backup-frequency', async (req, res) => {
    try {
      if (INSTANCE_TYPE === 'public') {
        return res.status(403).json({ message: 'Backups are not available in public mode' })
      }
      const { writeBackupFrequencyDays, scheduleBackups } = require('../utils/backup')
      const days = Number(req.body?.days || 0)
      if (!Number.isFinite(days) || days < 0) return res.status(400).json({ message: 'Invalid days' })
      writeBackupFrequencyDays(days)
      scheduleBackups(days, prisma)
      return res.json({ message: 'Backup frequency updated', days })
    } catch {
      return res.status(500).json({ message: 'Failed to update backup frequency' })
    }
  })

  router.post('/backup-now', async (req, res) => {
    try {
      if (INSTANCE_TYPE === 'public') {
        return res.status(403).json({ message: 'Backups are not available in public mode' })
      }
      const { performBackupOnce } = require('../utils/backup')
      await performBackupOnce(prisma)
      return res.json({ message: 'Backup started' })
    } catch {
      return res.status(500).json({ message: 'Failed to start backup' })
    }
  })

  // Sync settings endpoints - available in all modes
  const {
    readSyncFrequencyMinutes,
    writeSyncFrequencyMinutes,
    scheduleSyncs
  } = require('../utils/syncScheduler');

  // Per-account sync settings (AUTH mode)
  router.get('/account-sync', async (req, res) => {
    try {
      if (INSTANCE_TYPE !== 'public') {
        const account = await ensureDefaultAccount()
        let syncCfg = account?.sync
        if (syncCfg && typeof syncCfg === 'string') {
          try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null }
        }

        const minutes = readSyncFrequencyMinutes()
        const derivedFrequency = minutes === 1 ? '1m' : (minutes >= 1440 ? `${Math.round(minutes / 1440)}d` : `${minutes}m`)

        const enabled = syncCfg && typeof syncCfg === 'object'
          ? syncCfg.enabled !== false
          : minutes > 0

        const response = {
          enabled,
          frequency: (syncCfg && typeof syncCfg === 'object' && syncCfg.frequency) ? String(syncCfg.frequency).trim() : derivedFrequency,
          safe: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.safe === 'boolean') ? syncCfg.safe : true,
          mode: (syncCfg && typeof syncCfg === 'object' && syncCfg.mode === 'advanced') ? 'advanced' : 'normal',
          webhookUrl: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.webhookUrl === 'string') ? syncCfg.webhookUrl : '',
          useCustomFields: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.useCustomFields === 'boolean') ? syncCfg.useCustomFields : ((syncCfg && typeof syncCfg === 'object' && typeof syncCfg.useCustomNames === 'boolean') ? syncCfg.useCustomNames : false),
          notifyOnActivity: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnActivity === true : false,
          notifyOnSync: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnSync === true : false,
          notifyOnInvite: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnInvite === true : false,
          notifyOnVault: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnVault === true : false,
          notifyOnAddonHealth: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnAddonHealth === true : false,
          notifyOnBackup: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnBackup === true : false,
          notifyOnProxyHealth: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnProxyHealth === true : false,
          notifyOnUpdateAvailable: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnUpdateAvailable === true : false,
          notifyOnMosaic: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnMosaic === true : false,
          // Default true, unlike every notify toggle above - an automation
          // notification only exists because the admin explicitly wrote a rule
          // whose action is "notify me," so defaulting it off would mean that
          // rule silently does nothing until Settings is opened once.
          notifyOnAutomation: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.notifyOnAutomation === 'boolean') ? syncCfg.notifyOnAutomation : true,
          notifyDigestEnabled: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyDigestEnabled === true : false,
          notifyDigestFrequency: (syncCfg && typeof syncCfg === 'object' && syncCfg.notifyDigestFrequency === 'weekly') ? 'weekly' : 'daily',
          accountTimezone: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.accountTimezone === 'string' && syncCfg.accountTimezone.trim()) ? syncCfg.accountTimezone.trim() : DEFAULT_TIMEZONE,
          // True when nobody has ever explicitly saved a timezone - lets the
          // client silently auto-fill its browser-detected zone once instead
          // of leaving it on the bare env-var/hardcoded fallback forever.
          accountTimezoneIsDefault: !(syncCfg && typeof syncCfg === 'object' && typeof syncCfg.accountTimezone === 'string' && syncCfg.accountTimezone.trim()),
          vaultCurrency: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.vaultCurrency === 'string' && syncCfg.vaultCurrency.trim()) ? syncCfg.vaultCurrency.trim() : 'USD',
          // SlickTrax features (v1.29-v1.30, named "Personal Features" pre-v1.37).
          // All default true so existing installs get the same behavior; a
          // user who explicitly turns any off (Settings → SlickTrax) hides
          // the corresponding UI.
          enableWatchlist: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.enableWatchlist === 'boolean') ? syncCfg.enableWatchlist : true,
          enableWatchedIndicators: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.enableWatchedIndicators === 'boolean') ? syncCfg.enableWatchedIndicators : true,
          enableRecommendations: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.enableRecommendations === 'boolean') ? syncCfg.enableRecommendations : true,
          // Opt-in, not opt-out (unlike the other SlickTrax toggles above) -
          // autoplaying a trailer the moment a title's modal opens is
          // disruptive enough that a first-time visitor shouldn't get it by
          // default; explicitly turning it on in Settings is the ask.
          enableAutoplayTrailer: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.enableAutoplayTrailer === 'boolean') ? syncCfg.enableAutoplayTrailer : false,
          autoplayTrailerStartMuted: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.autoplayTrailerStartMuted === 'boolean') ? syncCfg.autoplayTrailerStartMuted : true,
          enablePosterRatings: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.enablePosterRatings === 'boolean') ? syncCfg.enablePosterRatings : false,
          enableReactions: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.enableReactions === 'boolean') ? syncCfg.enableReactions : true,
          // Opt-in, not opt-out (like enableAutoplayTrailer above) - auto-
          // generating and persisting a new Catalog from a detected taste
          // cluster is a bigger, more visible change than a scrolling
          // recommendation row, so it needs an explicit "yes" in Settings.
          enableAutoThemedCatalogs: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.enableAutoThemedCatalogs === 'boolean') ? syncCfg.enableAutoThemedCatalogs : false,
          tmdbApiKey: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.tmdbApiKey === 'string') ? syncCfg.tmdbApiKey : '',
          mdblistApiKey: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.mdblistApiKey === 'string') ? syncCfg.mdblistApiKey : '',
          rpdbApiKey: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.rpdbApiKey === 'string') ? syncCfg.rpdbApiKey : '',
          omdbApiKey: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.omdbApiKey === 'string') ? syncCfg.omdbApiKey : '',
          simklClientId: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.simklClientId === 'string') ? syncCfg.simklClientId : '',
        }

        return res.json(response)
      }
      const acc = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { sync: true } })
      let syncCfg = acc?.sync || null
      if (syncCfg && typeof syncCfg === 'string') {
        try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null }
      }
      if (syncCfg && typeof syncCfg === 'object') {
        const safe = (typeof syncCfg.safe === 'boolean') ? syncCfg.safe : !syncCfg.unsafe
        const mode = syncCfg.mode === 'advanced' ? 'advanced' : 'normal'
        const frequency = (typeof syncCfg.frequency === 'string' && syncCfg.frequency.trim())
          ? syncCfg.frequency.trim()
          : '0'
        const resp = {
          enabled: syncCfg.enabled !== false, safe, mode, frequency, lastRunAt: syncCfg.lastRunAt,
          webhookUrl: syncCfg.webhookUrl || '',
          useCustomFields: (typeof syncCfg.useCustomFields === 'boolean') ? syncCfg.useCustomFields : ((typeof syncCfg.useCustomNames === 'boolean') ? syncCfg.useCustomNames : false),
          notifyOnActivity: syncCfg.notifyOnActivity === true,
          notifyOnSync: syncCfg.notifyOnSync === true,
          notifyOnInvite: syncCfg.notifyOnInvite === true,
          notifyOnVault: syncCfg.notifyOnVault === true,
          notifyOnAddonHealth: syncCfg.notifyOnAddonHealth === true,
          notifyOnBackup: syncCfg.notifyOnBackup === true,
          notifyOnProxyHealth: syncCfg.notifyOnProxyHealth === true,
          notifyOnUpdateAvailable: syncCfg.notifyOnUpdateAvailable === true,
          notifyOnMosaic: syncCfg.notifyOnMosaic === true,
          notifyOnAutomation: typeof syncCfg.notifyOnAutomation === 'boolean' ? syncCfg.notifyOnAutomation : true,
          notifyDigestEnabled: syncCfg.notifyDigestEnabled === true,
          notifyDigestFrequency: syncCfg.notifyDigestFrequency === 'weekly' ? 'weekly' : 'daily',
          accountTimezone: (typeof syncCfg.accountTimezone === 'string' && syncCfg.accountTimezone.trim()) ? syncCfg.accountTimezone.trim() : DEFAULT_TIMEZONE,
          accountTimezoneIsDefault: !(typeof syncCfg.accountTimezone === 'string' && syncCfg.accountTimezone.trim()),
          vaultCurrency: (typeof syncCfg.vaultCurrency === 'string' && syncCfg.vaultCurrency.trim()) ? syncCfg.vaultCurrency.trim() : 'USD',
          enableWatchlist: typeof syncCfg.enableWatchlist === 'boolean' ? syncCfg.enableWatchlist : true,
          enableWatchedIndicators: typeof syncCfg.enableWatchedIndicators === 'boolean' ? syncCfg.enableWatchedIndicators : true,
          enableRecommendations: typeof syncCfg.enableRecommendations === 'boolean' ? syncCfg.enableRecommendations : true,
          enableAutoplayTrailer: typeof syncCfg.enableAutoplayTrailer === 'boolean' ? syncCfg.enableAutoplayTrailer : false,
          autoplayTrailerStartMuted: typeof syncCfg.autoplayTrailerStartMuted === 'boolean' ? syncCfg.autoplayTrailerStartMuted : true,
          enablePosterRatings: typeof syncCfg.enablePosterRatings === 'boolean' ? syncCfg.enablePosterRatings : false,
          enableReactions: typeof syncCfg.enableReactions === 'boolean' ? syncCfg.enableReactions : true,
          enableAutoThemedCatalogs: typeof syncCfg.enableAutoThemedCatalogs === 'boolean' ? syncCfg.enableAutoThemedCatalogs : false,
          tmdbApiKey: typeof syncCfg.tmdbApiKey === 'string' ? syncCfg.tmdbApiKey : '',
          mdblistApiKey: typeof syncCfg.mdblistApiKey === 'string' ? syncCfg.mdblistApiKey : '',
          rpdbApiKey: typeof syncCfg.rpdbApiKey === 'string' ? syncCfg.rpdbApiKey : '',
          omdbApiKey: typeof syncCfg.omdbApiKey === 'string' ? syncCfg.omdbApiKey : '',
          simklClientId: typeof syncCfg.simklClientId === 'string' ? syncCfg.simklClientId : '',
        }
        return res.json(resp)
      }
      return res.json({ enabled: false, frequency: 0, safe: true, mode: 'normal', useCustomFields: false, notifyOnActivity: false, notifyOnSync: false, notifyOnInvite: false, notifyOnVault: false, notifyOnAddonHealth: false, notifyOnBackup: false, notifyOnProxyHealth: false, notifyOnUpdateAvailable: false, notifyOnMosaic: false, notifyOnAutomation: true, notifyDigestEnabled: false, notifyDigestFrequency: 'daily', accountTimezone: DEFAULT_TIMEZONE, accountTimezoneIsDefault: true, vaultCurrency: 'USD', enableWatchlist: true, enableWatchedIndicators: true, enableRecommendations: true, enableAutoplayTrailer: false, autoplayTrailerStartMuted: true, enablePosterRatings: false, enableReactions: true, enableAutoThemedCatalogs: false })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to read account sync settings' })
    }
  })

  router.put('/account-sync', async (req, res) => {
    try {
      const { enabled, frequency, mode, unsafe, safe, webhookUrl, useCustomFields, useCustomNames, notifyOnActivity, notifyOnSync, notifyOnInvite, notifyOnVault, notifyOnAddonHealth, notifyOnBackup, notifyOnProxyHealth, notifyOnUpdateAvailable, notifyOnMosaic, notifyOnAutomation, notifyDigestEnabled, notifyDigestFrequency, accountTimezone, vaultCurrency, enableWatchlist, enableWatchedIndicators, enableRecommendations, enableAutoplayTrailer, autoplayTrailerStartMuted, enablePosterRatings, enableReactions, enableAutoThemedCatalogs, tmdbApiKey, mdblistApiKey, rpdbApiKey, omdbApiKey, simklClientId } = req.body || {}
      // Support both useCustomFields (new) and useCustomNames (old) for backward compatibility
      const useCustomFieldsValue = useCustomFields !== undefined ? useCustomFields : useCustomNames
      if (INSTANCE_TYPE !== 'public') {
        await ensureDefaultAccount()
        const safeMinutes = (() => {
          if (frequency === undefined || frequency === null) return null
          if (typeof frequency === 'number') return frequency
          if (typeof frequency === 'string') {
            const trimmed = frequency.trim().toLowerCase()
            if (trimmed.endsWith('d')) {
              const days = Number(trimmed.slice(0, -1))
              return Number.isFinite(days) && days > 0 ? days * 1440 : null
            }
            if (trimmed.endsWith('h')) {
              const hours = Number(trimmed.slice(0, -1))
              return Number.isFinite(hours) && hours > 0 ? hours * 60 : null
            }
            if (trimmed.endsWith('m')) {
              const mins = Number(trimmed.slice(0, -1))
              return Number.isFinite(mins) && mins >= 0 ? mins : null
            }
            const raw = Number(trimmed)
            return Number.isFinite(raw) && raw >= 0 ? raw : null
          }
          return null
        })()

        if (safeMinutes !== null && safeMinutes < 0) {
          return res.status(400).json({ message: 'Invalid frequency value' })
        }

        const nextMinutes = enabled === false ? 0 : (safeMinutes ?? readSyncFrequencyMinutes())
        if (!Number.isFinite(nextMinutes) || nextMinutes < 0) {
          return res.status(400).json({ message: 'Invalid minutes' })
        }

        writeSyncFrequencyMinutes(nextMinutes)

        const current = await prisma.appAccount.findUnique({ where: { id: DEFAULT_ACCOUNT_ID }, select: { sync: true } })
        let syncCfg = current?.sync
        if (syncCfg && typeof syncCfg === 'string') {
          try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null }
        }
        const baseCfg = (syncCfg && typeof syncCfg === 'object') ? syncCfg : {}
        const nextCfg = {
          ...baseCfg,
          enabled: enabled === undefined ? baseCfg.enabled !== false : !!enabled,
          frequency: typeof frequency === 'string' && frequency.trim() ? frequency.trim() : baseCfg.frequency || '0',
          safe: safe !== undefined ? !!safe : (unsafe !== undefined ? !unsafe : baseCfg.safe !== false),
          mode: mode === 'advanced' ? 'advanced' : baseCfg.mode === 'advanced' ? 'advanced' : 'normal',
          webhookUrl: webhookUrl !== undefined ? (webhookUrl || null) : (baseCfg.webhookUrl || null),
          useCustomFields: useCustomFieldsValue !== undefined ? !!useCustomFieldsValue : ((baseCfg.useCustomFields !== undefined ? baseCfg.useCustomFields : (baseCfg.useCustomNames !== undefined ? baseCfg.useCustomNames : false))),
          notifyOnActivity: notifyOnActivity !== undefined ? !!notifyOnActivity : ((baseCfg.notifyOnActivity !== undefined) ? baseCfg.notifyOnActivity : false),
          notifyOnSync: notifyOnSync !== undefined ? !!notifyOnSync : ((baseCfg.notifyOnSync !== undefined) ? baseCfg.notifyOnSync : false),
          notifyOnInvite: notifyOnInvite !== undefined ? !!notifyOnInvite : ((baseCfg.notifyOnInvite !== undefined) ? baseCfg.notifyOnInvite : false),
          notifyOnVault: notifyOnVault !== undefined ? !!notifyOnVault : ((baseCfg.notifyOnVault !== undefined) ? baseCfg.notifyOnVault : false),
          notifyOnAddonHealth: notifyOnAddonHealth !== undefined ? !!notifyOnAddonHealth : ((baseCfg.notifyOnAddonHealth !== undefined) ? baseCfg.notifyOnAddonHealth : false),
          notifyOnBackup: notifyOnBackup !== undefined ? !!notifyOnBackup : ((baseCfg.notifyOnBackup !== undefined) ? baseCfg.notifyOnBackup : false),
          notifyOnProxyHealth: notifyOnProxyHealth !== undefined ? !!notifyOnProxyHealth : ((baseCfg.notifyOnProxyHealth !== undefined) ? baseCfg.notifyOnProxyHealth : false),
          notifyOnUpdateAvailable: notifyOnUpdateAvailable !== undefined ? !!notifyOnUpdateAvailable : ((baseCfg.notifyOnUpdateAvailable !== undefined) ? baseCfg.notifyOnUpdateAvailable : false),
          notifyOnMosaic: notifyOnMosaic !== undefined ? !!notifyOnMosaic : ((baseCfg.notifyOnMosaic !== undefined) ? baseCfg.notifyOnMosaic : false),
          notifyOnAutomation: notifyOnAutomation !== undefined ? !!notifyOnAutomation : (typeof baseCfg.notifyOnAutomation === 'boolean' ? baseCfg.notifyOnAutomation : true),
          notifyDigestEnabled: notifyDigestEnabled !== undefined ? !!notifyDigestEnabled : ((baseCfg.notifyDigestEnabled !== undefined) ? baseCfg.notifyDigestEnabled : false),
          notifyDigestFrequency: notifyDigestFrequency === 'weekly' ? 'weekly' : (notifyDigestFrequency === 'daily' ? 'daily' : (baseCfg.notifyDigestFrequency === 'weekly' ? 'weekly' : 'daily')),
          accountTimezone: typeof accountTimezone === 'string' && accountTimezone.trim() ? accountTimezone.trim() : (baseCfg.accountTimezone || DEFAULT_TIMEZONE),
          vaultCurrency: typeof vaultCurrency === 'string' && vaultCurrency.trim() ? vaultCurrency.trim().toUpperCase() : (baseCfg.vaultCurrency || 'USD'),
          enableWatchlist: enableWatchlist !== undefined ? !!enableWatchlist : (typeof baseCfg.enableWatchlist === 'boolean' ? baseCfg.enableWatchlist : true),
          enableWatchedIndicators: enableWatchedIndicators !== undefined ? !!enableWatchedIndicators : (typeof baseCfg.enableWatchedIndicators === 'boolean' ? baseCfg.enableWatchedIndicators : true),
          enableRecommendations: enableRecommendations !== undefined ? !!enableRecommendations : (typeof baseCfg.enableRecommendations === 'boolean' ? baseCfg.enableRecommendations : true),
          enableAutoplayTrailer: enableAutoplayTrailer !== undefined ? !!enableAutoplayTrailer : (typeof baseCfg.enableAutoplayTrailer === 'boolean' ? baseCfg.enableAutoplayTrailer : false),
          autoplayTrailerStartMuted: autoplayTrailerStartMuted !== undefined ? !!autoplayTrailerStartMuted : (typeof baseCfg.autoplayTrailerStartMuted === 'boolean' ? baseCfg.autoplayTrailerStartMuted : true),
          enablePosterRatings: enablePosterRatings !== undefined ? !!enablePosterRatings : (typeof baseCfg.enablePosterRatings === 'boolean' ? baseCfg.enablePosterRatings : false),
          enableReactions: enableReactions !== undefined ? !!enableReactions : (typeof baseCfg.enableReactions === 'boolean' ? baseCfg.enableReactions : true),
          enableAutoThemedCatalogs: enableAutoThemedCatalogs !== undefined ? !!enableAutoThemedCatalogs : (typeof baseCfg.enableAutoThemedCatalogs === 'boolean' ? baseCfg.enableAutoThemedCatalogs : false),
          // Optional TMDb API key for the cast/crew deep-dive. Trimmed; empty
          // string clears it (falls back to the TMDB_API_KEY env var, if any).
          tmdbApiKey: tmdbApiKey !== undefined ? (typeof tmdbApiKey === 'string' ? tmdbApiKey.trim() : '') : (baseCfg.tmdbApiKey || ''),
          // Optional MDBList API key for List import. Free from mdblist.com ->
          // Preferences -> API Access.
          mdblistApiKey: mdblistApiKey !== undefined ? (typeof mdblistApiKey === 'string' ? mdblistApiKey.trim() : '') : (baseCfg.mdblistApiKey || ''),
          // Optional RPDB (RatingPosterDB) key - free tier works, upgrades
          // posters app-wide with rating-embedded art. Free at
          // ratingposterdb.com.
          rpdbApiKey: rpdbApiKey !== undefined ? (typeof rpdbApiKey === 'string' ? rpdbApiKey.trim() : '') : (baseCfg.rpdbApiKey || ''),
          // Optional OMDb key - free at omdbapi.com/apikey.aspx. Powers
          // Rotten Tomatoes/Metacritic ratings; per-account like the three
          // above it, so one account's key/quota isn't silently shared by
          // every other account on this instance.
          omdbApiKey: omdbApiKey !== undefined ? (typeof omdbApiKey === 'string' ? normalizeOmdbApiKey(omdbApiKey.trim()) : '') : (baseCfg.omdbApiKey || ''),
          simklClientId: simklClientId !== undefined ? (typeof simklClientId === 'string' ? simklClientId.trim() : '') : (baseCfg.simklClientId || ''),
        }

        try {
          await prisma.appAccount.update({ where: { id: DEFAULT_ACCOUNT_ID }, data: { sync: nextCfg } })
        } catch {
          await prisma.appAccount.update({ where: { id: DEFAULT_ACCOUNT_ID }, data: { sync: JSON.stringify(nextCfg) } })
        }

        const { reloadGroupAddons } = require('../routes/users')
        const scopedWhere = require('../utils/helpers').scopedWhere
        const decrypt = require('../utils/encryption').decrypt
        const schedulerReq = { appAccountId: DEFAULT_ACCOUNT_ID }
        scheduleSyncs(nextMinutes, prisma, getAccountId, scopedWhere, decrypt, reloadGroupAddons, schedulerReq, false)
        return res.json({ message: 'Sync settings updated' })
      }
      // Load current config to preserve unspecified fields
      const acc = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { sync: true } })
      let current = acc?.sync || null
      if (current && typeof current === 'string') { try { current = JSON.parse(current) } catch { current = null } }
      const base = (current && typeof current === 'object') ? current : {}

      // Build partial update only for provided fields
      const partial = {}
      if (enabled !== undefined) partial.enabled = !!enabled
      if (frequency !== undefined) partial.frequency = String(frequency)
      if (mode !== undefined) partial.mode = (mode === 'advanced') ? 'advanced' : 'normal'
      if (safe !== undefined) partial.safe = !!safe
      else if (unsafe !== undefined) partial.safe = !unsafe
      if (webhookUrl !== undefined) partial.webhookUrl = webhookUrl || null
      if (useCustomFieldsValue !== undefined) partial.useCustomFields = !!useCustomFieldsValue
      if (notifyOnActivity !== undefined) partial.notifyOnActivity = !!notifyOnActivity
      if (notifyOnSync !== undefined) partial.notifyOnSync = !!notifyOnSync
      if (notifyOnInvite !== undefined) partial.notifyOnInvite = !!notifyOnInvite
      if (notifyOnVault !== undefined) partial.notifyOnVault = !!notifyOnVault
      if (notifyOnAddonHealth !== undefined) partial.notifyOnAddonHealth = !!notifyOnAddonHealth
      if (notifyOnBackup !== undefined) partial.notifyOnBackup = !!notifyOnBackup
      if (notifyOnProxyHealth !== undefined) partial.notifyOnProxyHealth = !!notifyOnProxyHealth
      if (notifyOnUpdateAvailable !== undefined) partial.notifyOnUpdateAvailable = !!notifyOnUpdateAvailable
      if (notifyOnMosaic !== undefined) partial.notifyOnMosaic = !!notifyOnMosaic
      if (notifyOnAutomation !== undefined) partial.notifyOnAutomation = !!notifyOnAutomation
      if (notifyDigestEnabled !== undefined) partial.notifyDigestEnabled = !!notifyDigestEnabled
      if (notifyDigestFrequency !== undefined) partial.notifyDigestFrequency = notifyDigestFrequency === 'weekly' ? 'weekly' : 'daily'
      if (typeof accountTimezone === 'string' && accountTimezone.trim()) partial.accountTimezone = accountTimezone.trim()
      if (typeof vaultCurrency === 'string' && vaultCurrency.trim()) partial.vaultCurrency = vaultCurrency.trim().toUpperCase()
      if (enableWatchlist !== undefined) partial.enableWatchlist = !!enableWatchlist
      if (enableWatchedIndicators !== undefined) partial.enableWatchedIndicators = !!enableWatchedIndicators
      if (enableRecommendations !== undefined) partial.enableRecommendations = !!enableRecommendations
      if (enableAutoplayTrailer !== undefined) partial.enableAutoplayTrailer = !!enableAutoplayTrailer
      if (autoplayTrailerStartMuted !== undefined) partial.autoplayTrailerStartMuted = !!autoplayTrailerStartMuted
      if (enablePosterRatings !== undefined) partial.enablePosterRatings = !!enablePosterRatings
      if (enableReactions !== undefined) partial.enableReactions = !!enableReactions
      if (enableAutoThemedCatalogs !== undefined) partial.enableAutoThemedCatalogs = !!enableAutoThemedCatalogs
      if (tmdbApiKey !== undefined) partial.tmdbApiKey = typeof tmdbApiKey === 'string' ? tmdbApiKey.trim() : ''
      if (mdblistApiKey !== undefined) partial.mdblistApiKey = typeof mdblistApiKey === 'string' ? mdblistApiKey.trim() : ''
      if (rpdbApiKey !== undefined) partial.rpdbApiKey = typeof rpdbApiKey === 'string' ? rpdbApiKey.trim() : ''
      if (omdbApiKey !== undefined) partial.omdbApiKey = typeof omdbApiKey === 'string' ? normalizeOmdbApiKey(omdbApiKey.trim()) : ''
      if (simklClientId !== undefined) partial.simklClientId = typeof simklClientId === 'string' ? simklClientId.trim() : ''

      const nextCfg = { ...base, ...partial }

      // Persist JSON (Postgres) or stringified (SQLite)
      try {
        await prisma.appAccount.update({ where: { id: req.appAccountId }, data: { sync: nextCfg } })
      } catch {
        await prisma.appAccount.update({ where: { id: req.appAccountId }, data: { sync: JSON.stringify(nextCfg) } })
      }
      // Reschedule heap with new config (scheduler will re-seed on next scheduleSyncs call)
      const { reloadGroupAddons } = require('../routes/users');
      const scopedWhere = require('../utils/helpers').scopedWhere;
      const decrypt = require('../utils/encryption').decrypt;
      scheduleSyncs(0, prisma, getAccountId, scopedWhere, decrypt, reloadGroupAddons, req, true) // clear
      scheduleSyncs(1, prisma, getAccountId, scopedWhere, decrypt, reloadGroupAddons, req, true) // re-seed; minutes ignored in AUTH mode
      return res.json({ message: 'Account sync settings updated' })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to update account sync settings', error: e?.message })
    }
  })

  // Theme preferences (account-scoped, so a theme choice made on one device
  // shows up on every other device signed into the same account). Stored on
  // AppAccount.sync.themePref — no schema migration needed. The shape is
  // deliberately loose (just JSON) so client-side additions (new fonts, extra
  // color overrides) don't require a server update.
  router.get('/theme-pref', async (req, res) => {
    try {
      const accountId = INSTANCE_TYPE === 'public' ? req.appAccountId : DEFAULT_ACCOUNT_ID
      if (!accountId) return res.status(401).json({ message: 'Unauthorized' })
      if (INSTANCE_TYPE !== 'public') await ensureDefaultAccount()
      const acc = await prisma.appAccount.findUnique({ where: { id: accountId }, select: { sync: true } })
      let syncCfg = acc?.sync
      if (typeof syncCfg === 'string') { try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null } }
      const themePref = (syncCfg && typeof syncCfg === 'object' && syncCfg.themePref && typeof syncCfg.themePref === 'object')
        ? syncCfg.themePref
        : null
      return res.json({ themePref })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to read theme preferences' })
    }
  })

  router.put('/theme-pref', async (req, res) => {
    try {
      const accountId = INSTANCE_TYPE === 'public' ? req.appAccountId : DEFAULT_ACCOUNT_ID
      if (!accountId) return res.status(401).json({ message: 'Unauthorized' })
      if (INSTANCE_TYPE !== 'public') await ensureDefaultAccount()
      const { themePref } = req.body || {}
      if (themePref !== null && (typeof themePref !== 'object' || Array.isArray(themePref))) {
        return res.status(400).json({ message: 'themePref must be an object or null' })
      }
      const acc = await prisma.appAccount.findUnique({ where: { id: accountId }, select: { sync: true } })
      let syncCfg = acc?.sync
      if (typeof syncCfg === 'string') { try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null } }
      if (!syncCfg || typeof syncCfg !== 'object') syncCfg = {}
      const nextCfg = { ...syncCfg, themePref: themePref || undefined }
      try { await prisma.appAccount.update({ where: { id: accountId }, data: { sync: nextCfg } }) }
      catch { await prisma.appAccount.update({ where: { id: accountId }, data: { sync: JSON.stringify(nextCfg) } }) }
      return res.json({ themePref })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to save theme preferences' })
    }
  })

  router.post('/account-sync/test-webhook', async (req, res) => {
    try {
      const providedUrl = typeof req.body?.webhookUrl === 'string' ? req.body.webhookUrl.trim() : ''
      let targetUrl = providedUrl

      const readAccountWebhook = async (accountId) => {
        const acc = await prisma.appAccount.findUnique({ where: { id: accountId }, select: { sync: true } })
        if (!acc) return null
        let syncCfg = acc.sync
        if (typeof syncCfg === 'string') {
          try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null }
        }
        if (syncCfg && typeof syncCfg === 'object' && syncCfg.webhookUrl) {
          return String(syncCfg.webhookUrl)
        }
        return null
      }

      if (!targetUrl) {
        if (INSTANCE_TYPE === 'public') {
          if (!req.appAccountId) {
            return res.status(401).json({ message: 'Unauthorized' })
          }
          targetUrl = await readAccountWebhook(req.appAccountId)
        } else {
          await ensureDefaultAccount()
          targetUrl = await readAccountWebhook(DEFAULT_ACCOUNT_ID)
        }
      }

      if (!targetUrl) {
        return res.status(400).json({ message: 'No webhook URL configured' })
      }

      await postDiscord(targetUrl, '🔬 SlickSync test webhook message')
      return res.json({ message: 'Test message sent' })
    } catch (e) {
      console.error('Failed to send webhook test:', e)
      return res.status(500).json({ message: 'Failed to send test message', error: e?.message })
    }
  })

  // Manual sync trigger
  router.post('/sync-now', async (req, res) => {
    try {
      const { syncGroupUsers } = require('../routes/groups');
      const scopedWhere = require('../utils/helpers').scopedWhere;
      const decrypt = require('../utils/encryption').decrypt;

      const accountId = INSTANCE_TYPE === 'public' ? req.appAccountId : DEFAULT_ACCOUNT_ID;
      const syncReq = { appAccountId: accountId, headers: {}, body: {} };

      const groups = await prisma.group.findMany({
        where: scopedWhere(syncReq, {}),
        select: { id: true }
      });

      if (groups.length === 0) {
        return res.json({ message: 'No groups found to sync', syncedGroups: 0, failedGroups: 0, totalGroups: 0 });
      }

      let syncedGroups = 0;
      let failedGroups = 0;

      for (const group of groups) {
        try {
          const result = await syncGroupUsers(prisma, getAccountId, scopedWhere, decrypt, group.id, syncReq);
          if (result?.error) {
            failedGroups++;
          } else {
            syncedGroups++;
          }
        } catch (e) {
          failedGroups++;
        }
      }

      return res.json({
        message: 'Sync completed',
        syncedGroups,
        failedGroups,
        totalGroups: groups.length
      });
    } catch (e) {
      return res.status(500).json({ message: 'Failed to start sync', error: e?.message })
    }
  })

  // API Key management (generate/revoke)
  router.get('/account-api', async (req, res) => {
    try {
      const acc = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { apiKeyHash: true } })
      if (!acc?.apiKeyHash) {
        return res.json({ hasKey: false, apiKey: null })
      }
      // Decrypt using account-specific key (accountId + server key)
      try {
        const { getServerKey, aesGcmDecrypt } = require('../utils/encryption')
        const serverKey = getServerKey()
        const accountKey = require('crypto').createHash('sha256').update(Buffer.concat([Buffer.from(req.appAccountId || ''), serverKey])).digest()
        const decrypted = aesGcmDecrypt(accountKey, acc.apiKeyHash)
        return res.json({ hasKey: true, apiKey: decrypted })
      } catch (e) {
        // If decryption fails, key might be in old format - treat as no key
        return res.json({ hasKey: false, apiKey: null })
      }
    } catch {
      return res.status(500).json({ message: 'Failed to read API key status' })
    }
  })

  router.post('/account-api-key', async (req, res) => {
    try {
      if (!req.appAccountId) {
        return res.status(401).json({ message: 'Unauthorized' })
      }
      const { generateApiKey } = require('../utils/apiKey')
      const { getServerKey, aesGcmEncrypt } = require('../utils/encryption')
      const key = generateApiKey()
      // Encrypt using account-specific key (accountId + server key)
      const serverKey = getServerKey()
      const accountKey = require('crypto').createHash('sha256').update(Buffer.concat([Buffer.from(req.appAccountId || ''), serverKey])).digest()
      const encrypted = aesGcmEncrypt(accountKey, key)
      await prisma.appAccount.update({ where: { id: req.appAccountId }, data: { apiKeyHash: encrypted } })
      // Return the full key ONCE
      return res.json({ apiKey: key })
    } catch (e) {
      console.error('Error generating API key:', e)
      return res.status(500).json({ message: 'Failed to generate API key', error: e?.message })
    }
  })

  router.delete('/account-api-key', async (req, res) => {
    try {
      await prisma.appAccount.update({ where: { id: req.appAccountId }, data: { apiKeyHash: null } })
      return res.json({ message: 'API key revoked' })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to revoke API key' })
    }
  })

  // 2FA (TOTP) - opt-in per account. See server/utils/twoFactor.js for the
  // pending-challenge design that keeps the login-time verification step
  // from ever looking like a real session token.
  const twoFactor = require('../utils/twoFactor')

  // GET /account-2fa - current status only, never the secret itself.
  router.get('/account-2fa', async (req, res) => {
    try {
      const acc = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { twoFactorEnabled: true } })
      return res.json({ enabled: !!acc?.twoFactorEnabled })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to read 2FA status' })
    }
  })

  // POST /account-2fa/setup - generates a new secret + QR, does NOT persist
  // or enable anything yet. The client must round-trip the secret back to
  // /account-2fa/enable along with a real code from it, proving the user
  // actually scanned/saved it, before it's turned on.
  router.post('/account-2fa/setup', async (req, res) => {
    try {
      const acc = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { email: true, uuid: true, twoFactorEnabled: true } })
      if (acc?.twoFactorEnabled) return res.status(400).json({ message: '2FA is already enabled - disable it first to set up a new device' })
      const secret = twoFactor.generateSecret()
      const label = acc?.email || acc?.uuid || req.appAccountId
      const url = twoFactor.otpauthUrl(secret, label)
      const qrCodeDataUrl = await twoFactor.qrCodeDataUrl(url)
      return res.json({ secret, otpauthUrl: url, qrCodeDataUrl })
    } catch (e) {
      console.error('Error starting 2FA setup:', e)
      return res.status(500).json({ message: 'Failed to start 2FA setup' })
    }
  })

  // POST /account-2fa/enable { secret, code } - verifies the code against
  // the secret the client got from /setup, then persists (encrypted) and
  // turns 2FA on. Returns the backup codes in plaintext ONCE.
  router.post('/account-2fa/enable', async (req, res) => {
    try {
      const { secret, code } = req.body || {}
      if (!secret || !code) return res.status(400).json({ message: 'secret and code are required' })
      if (!twoFactor.verifyTotp(secret, code)) return res.status(400).json({ message: 'Incorrect code - check your authenticator app and try again' })

      const backupCodes = twoFactor.generateBackupCodes()
      const hashed = await twoFactor.hashBackupCodes(backupCodes)
      await prisma.appAccount.update({
        where: { id: req.appAccountId },
        data: {
          twoFactorEnabled: true,
          twoFactorSecret: twoFactor.encryptSecret(req.appAccountId, secret),
          twoFactorBackupCodes: JSON.stringify(hashed),
        },
      })
      return res.json({ enabled: true, backupCodes })
    } catch (e) {
      console.error('Error enabling 2FA:', e)
      return res.status(500).json({ message: 'Failed to enable 2FA' })
    }
  })

  // POST /account-2fa/disable { code } - requires a valid TOTP or backup
  // code, not just an active session, so a hijacked session alone can't
  // turn off the second factor.
  router.post('/account-2fa/disable', async (req, res) => {
    try {
      const { code } = req.body || {}
      const acc = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { twoFactorEnabled: true, twoFactorSecret: true, twoFactorBackupCodes: true } })
      if (!acc?.twoFactorEnabled) return res.status(400).json({ message: '2FA is not enabled' })
      if (!code) return res.status(400).json({ message: 'code is required' })

      const secret = twoFactor.decryptSecret(req.appAccountId, acc.twoFactorSecret)
      const validTotp = twoFactor.verifyTotp(secret, code)
      let validBackup = false
      if (!validTotp && acc.twoFactorBackupCodes) {
        const hashed = JSON.parse(acc.twoFactorBackupCodes)
        validBackup = !!(await twoFactor.consumeBackupCode(hashed, code))
      }
      if (!validTotp && !validBackup) return res.status(400).json({ message: 'Incorrect code' })

      await prisma.appAccount.update({
        where: { id: req.appAccountId },
        data: { twoFactorEnabled: false, twoFactorSecret: null, twoFactorBackupCodes: null },
      })
      return res.json({ enabled: false })
    } catch (e) {
      console.error('Error disabling 2FA:', e)
      return res.status(500).json({ message: 'Failed to disable 2FA' })
    }
  })

  // POST /account-2fa/backup-codes { code } - same 2FA-gated pattern as
  // disable above; invalidates every existing backup code (including
  // unused ones) so an old leaked list stops working the moment new ones
  // are generated.
  router.post('/account-2fa/backup-codes', async (req, res) => {
    try {
      const { code } = req.body || {}
      const acc = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { twoFactorEnabled: true, twoFactorSecret: true } })
      if (!acc?.twoFactorEnabled) return res.status(400).json({ message: '2FA is not enabled' })
      if (!code) return res.status(400).json({ message: 'code is required' })

      const secret = twoFactor.decryptSecret(req.appAccountId, acc.twoFactorSecret)
      if (!twoFactor.verifyTotp(secret, code)) return res.status(400).json({ message: 'Incorrect code' })

      const backupCodes = twoFactor.generateBackupCodes()
      const hashed = await twoFactor.hashBackupCodes(backupCodes)
      await prisma.appAccount.update({ where: { id: req.appAccountId }, data: { twoFactorBackupCodes: JSON.stringify(hashed) } })
      return res.json({ backupCodes })
    } catch (e) {
      console.error('Error regenerating 2FA backup codes:', e)
      return res.status(500).json({ message: 'Failed to regenerate backup codes' })
    }
  })

  // Repair addons metadata (fill missing stremioAddonId and iconUrl from manifest)
  // Scopes to current account when AUTH is enabled
  router.post('/repair-addons', async (req, res) => {
    try {
      const whereScope = INSTANCE_TYPE === 'public' && req.appAccountId ? { accountId: req.appAccountId } : {}
      const addons = await prisma.addon.findMany({ where: whereScope })
      const { repairAddonsList } = require('../utils/repair')
      const result = await repairAddonsList({
        prisma,
        INSTANCE_TYPE,
        getAccountDek,
        getDecryptedManifestUrl,
        filterManifestByResources: require('../utils/stremio').filterManifestByResources,
        filterManifestByCatalogs: require('../utils/stremio').filterManifestByCatalogs,
        manifestHash: require('../utils/stremio').manifestHash,
        encrypt: require('../utils/encryption').encrypt
      }, req, addons)

      return res.json({ message: 'Repair completed', ...result })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to repair addons', error: e?.message })
    }
  })

  // Addon health check settings endpoints
  const { 
    getHealthCheckIntervalMinutes,
    triggerManualHealthCheck 
  } = require('../utils/addonHealthCheck');

  // Get health check interval setting
  router.get('/addon-health-check', async (req, res) => {
    try {
      const intervalMinutes = getHealthCheckIntervalMinutes();
      return res.json({ 
        enabled: intervalMinutes >= 1,
        intervalMinutes 
      });
    } catch (e) {
      return res.status(500).json({ message: 'Failed to read health check settings' });
    }
  });

  // Update health check interval (requires restart to take effect)
  router.put('/addon-health-check', async (req, res) => {
    try {
      const { intervalMinutes } = req.body || {};
      
      if (intervalMinutes === undefined) {
        return res.status(400).json({ message: 'intervalMinutes is required' });
      }
      
      const parsed = parseInt(intervalMinutes, 10);
      if (isNaN(parsed) || parsed < 0) {
        return res.status(400).json({ message: 'Invalid intervalMinutes value' });
      }
      
      // Store in environment variable for now
      // In production, this would ideally be stored in the database
      process.env.ADDON_HEALTH_CHECK_INTERVAL_MINUTES = String(parsed);
      
      return res.json({ 
        message: 'Health check interval updated. Restart server to apply changes.',
        intervalMinutes: parsed,
        enabled: parsed >= 1
      });
    } catch (e) {
      return res.status(500).json({ message: 'Failed to update health check settings', error: e?.message });
    }
  });

  // Trigger manual health check
  router.post('/addon-health-check/now', async (req, res) => {
    try {
      // Run in background
      const accountId = INSTANCE_TYPE === 'public' ? req.appAccountId : DEFAULT_ACCOUNT_ID;
      triggerManualHealthCheck(prisma, accountId);
      
      return res.json({ message: 'Health check started' });
    } catch (e) {
      return res.status(500).json({ message: 'Failed to start health check', error: e?.message });
    }
  });

  // POST /settings/delete-account - self-service, irreversible. Public
  // multi-tenant mode only: private mode's "account" is the whole shared
  // instance, not a personal one a user should be able to wipe from a
  // settings toggle. Always deletes req.appAccountId (the caller's own,
  // resolved by the auth middleware from their session) - never an id from
  // the request body, so there is no way to target another account.
  router.post('/delete-account', async (req, res) => {
    try {
      if (INSTANCE_TYPE !== 'public') {
        return res.status(403).json({ message: 'Self-service account deletion is only available in public (multi-tenant) mode.' });
      }
      if (!req.appAccountId) {
        return res.status(401).json({ message: 'Not signed in' });
      }
      const { deleteAccountCascade } = require('../utils/accountDeletion');
      await deleteAccountCascade(prisma, req.appAccountId);
      return res.json({ deleted: true });
    } catch (e) {
      if (e.notFound) return res.status(404).json({ message: 'Account not found' });
      console.error('[Settings] Failed to delete account:', e?.message);
      return res.status(500).json({ message: 'Failed to delete account' });
    }
  });

  return router;
};
