const express = require('express');
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs')
const { decrypt, encrypt } = require('../utils/encryption')
const { DEFAULT_ACCOUNT_ID, DEFAULT_ACCOUNT_UUID } = require('../utils/config')
const { postDiscord } = require('../utils/notify')
const { DEFAULT_TIMEZONE } = require('../utils/dateUtils')

module.exports = ({ prisma, INSTANCE_TYPE, getAccountDek, getDecryptedManifestUrl, getAccountId }) => {
  const router = express.Router();

  const ensureDefaultAccount = async () => {
    const privatePassword = process.env.PRIVATE_ACCOUNT_PASSWORD || 'private-mode'
    const defaultSyncPayload = JSON.stringify({ enabled: false, frequency: '0', safe: true, mode: 'normal', webhookUrl: null, notifyOnActivity: false, notifyOnSync: false, notifyOnInvite: false })

    let account = await prisma.appAccount.findUnique({ where: { id: DEFAULT_ACCOUNT_ID } })
    if (!account) {
      const passwordHash = await bcrypt.hash(privatePassword, 12)
      account = await prisma.appAccount.create({
        data: {
          id: DEFAULT_ACCOUNT_ID,
          uuid: DEFAULT_ACCOUNT_UUID,
          passwordHash,
          sync: defaultSyncPayload
        }
      })
      return account
    }

    const updates = {}
    if (!account.uuid || account.uuid !== DEFAULT_ACCOUNT_UUID) {
      updates.uuid = DEFAULT_ACCOUNT_UUID
    }
    if (!account.passwordHash) {
      updates.passwordHash = await bcrypt.hash(privatePassword, 12)
    }
    if (!account.sync) {
      updates.sync = defaultSyncPayload
    }

    if (Object.keys(updates).length) {
      account = await prisma.appAccount.update({ where: { id: DEFAULT_ACCOUNT_ID }, data: updates })
    }

    return account
  }

  router.get('/account-info', async (req, res) => {
    try {
      if (INSTANCE_TYPE !== 'public') {
        const account = await ensureDefaultAccount()
        return res.json({
          id: DEFAULT_ACCOUNT_ID,
          uuid: account?.uuid || DEFAULT_ACCOUNT_UUID,
        })
      }

      if (!req.appAccountId) {
        return res.status(401).json({ message: 'Unauthorized' })
      }

      const account = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { id: true, uuid: true } })
      if (!account) {
        return res.status(404).json({ message: 'Account not found' })
      }
      return res.json(account)
    } catch (e) {
      return res.status(500).json({ message: 'Failed to load account info', error: e?.message })
    }
  })

  // PUT /account-avatar - set or clear the admin's own profile picture
  // (full URL or /uploads/avatars/<file> from the shared avatar upload endpoint)
  router.put('/account-avatar', async (req, res) => {
    try {
      const { avatarUrl } = req.body || {}
      const accountId = INSTANCE_TYPE !== 'public' ? (await ensureDefaultAccount()).id : req.appAccountId
      if (!accountId) {
        return res.status(401).json({ message: 'Unauthorized' })
      }
      await prisma.appAccount.update({ where: { id: accountId }, data: { avatarUrl: avatarUrl || null } })
      return res.json({ avatarUrl: avatarUrl || null })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to update avatar', error: e?.message })
    }
  })

  // Backup settings endpoints - only available in private mode
  if (INSTANCE_TYPE !== 'public') {
    // Use centralized backup utilities
    const {
      BACKUP_DIR,
      ensureBackupDir,
      readBackupFrequencyDays,
      writeBackupFrequencyDays,
      performBackupOnce,
      clearBackupSchedule,
      scheduleBackups
    } = require('../utils/backup');

    // Filenames are always generated by performBackupOnce() as
    // config-backup-<ISO-ish timestamp>.json - allow-listing that exact
    // shape (plus a plain path.basename check below) is defense against
    // path traversal via a crafted :filename param, since these three
    // routes read/write/delete files on disk from a URL segment.
    const isValidBackupFilename = (name) =>
      typeof name === 'string' &&
      /^config-backup-[0-9T-]+\.json$/.test(name) &&
      path.basename(name) === name;

    // GET /settings/backups - list backups on disk, newest first. Each
    // entry's `validation` comes from the sidecar file backupValidation.js
    // writes right after the backup itself - absent (not re-computed here)
    // for backups written before that existed.
    router.get('/backups', async (req, res) => {
      try {
        ensureBackupDir()
        const files = fs.readdirSync(BACKUP_DIR).filter(isValidBackupFilename)
        const backups = files.map((filename) => {
          const stat = fs.statSync(path.join(BACKUP_DIR, filename))
          let validation = null
          try {
            const validationFile = path.join(BACKUP_DIR, filename.replace(/\.json$/, '.validation.json'))
            if (fs.existsSync(validationFile)) validation = JSON.parse(fs.readFileSync(validationFile, 'utf8'))
          } catch {}
          return { filename, size: stat.size, createdAt: stat.mtime.toISOString(), validation }
        }).sort((a, b) => b.createdAt.localeCompare(a.createdAt))
        return res.json(backups)
      } catch (e) {
        return res.status(500).json({ message: 'Failed to list backups', error: e?.message })
      }
    })

    // GET /settings/backups/:filename/download - raw backup file
    router.get('/backups/:filename/download', async (req, res) => {
      try {
        if (!isValidBackupFilename(req.params.filename)) {
          return res.status(400).json({ message: 'Invalid backup filename' })
        }
        const filePath = path.join(BACKUP_DIR, req.params.filename)
        if (!fs.existsSync(filePath)) return res.status(404).json({ message: 'Backup not found' })
        return res.download(filePath, req.params.filename)
      } catch (e) {
        return res.status(500).json({ message: 'Failed to download backup', error: e?.message })
      }
    })

    // POST /settings/backups/:filename/restore - DESTRUCTIVE: replaces all
    // current users/groups/addons with the backup's contents. Reads the
    // file server-side and forwards it into the existing, already-battle-
    // tested /public-auth/config-import handler (same internal-fetch
    // pattern performBackupOnce() already uses to call sibling endpoints)
    // rather than duplicating its import-ordering logic here.
    router.post('/backups/:filename/restore', async (req, res) => {
      try {
        if (!isValidBackupFilename(req.params.filename)) {
          return res.status(400).json({ message: 'Invalid backup filename' })
        }
        const filePath = path.join(BACKUP_DIR, req.params.filename)
        if (!fs.existsSync(filePath)) return res.status(404).json({ message: 'Backup not found' })

        const jsonData = fs.readFileSync(filePath, 'utf8')
        const baseUrl = `http://localhost:${process.env.PORT || 4000}`
        const rsp = await fetch(`${baseUrl}/api/public-auth/config-import`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ jsonData }),
        })
        const result = await rsp.json().catch(() => ({}))
        if (!rsp.ok) {
          return res.status(rsp.status).json(result?.message ? result : { message: 'Restore failed' })
        }
        return res.json(result)
      } catch (e) {
        return res.status(500).json({ message: 'Failed to restore backup', error: e?.message })
      }
    })

    // POST /settings/disaster-recovery-kit/export - unlike the regular
    // config backup above (Users/Groups/Addons only), this also bundles
    // every Vault secret, decrypted and re-encrypted under the passphrase
    // supplied here instead of this instance's own ENCRYPTION_KEY - so the
    // resulting file is portable to a brand-new instance if this one and
    // its key are both lost. Manual/on-demand only, never scheduled.
    router.post('/disaster-recovery-kit/export', async (req, res) => {
      try {
        const accountId = getAccountId(req) || 'default'
        const { passphrase } = req.body || {}
        const { buildKit } = require('../utils/disasterRecoveryKit')
        const kit = await buildKit(prisma, accountId, passphrase, req, { decrypt })
        res.setHeader('Content-Disposition', `attachment; filename="slicksync-recovery-kit-${new Date().toISOString().split('T')[0]}.json"`)
        return res.json(kit)
      } catch (e) {
        return res.status(400).json({ message: e?.message || 'Failed to build recovery kit' })
      }
    })

    // POST /settings/disaster-recovery-kit/import - DESTRUCTIVE, same as
    // restore-from-backup (replaces current Users/Groups/Addons), PLUS
    // creates a new Vault entry for every secret in the kit, re-encrypted
    // under THIS instance's own current ENCRYPTION_KEY.
    router.post('/disaster-recovery-kit/import', async (req, res) => {
      try {
        const accountId = getAccountId(req) || 'default'
        const { passphrase, kit } = req.body || {}
        const { restoreKit } = require('../utils/disasterRecoveryKit')
        const result = await restoreKit(prisma, accountId, passphrase, kit, req, { encrypt })
        return res.json(result)
      } catch (e) {
        return res.status(400).json({ message: e?.message || 'Failed to restore recovery kit' })
      }
    })

    // POST /settings/mosaic/generate-now - manual trigger for the monthly
    // poster mosaic, mainly so the feature can be tried/tested without
    // waiting for the scheduler's own month-rollover check. Defaults to the
    // most recently completed month (same target the scheduler picks);
    // optionally accepts { month: "YYYY-MM" } to regenerate/test a specific
    // one. Requires notifyOnMosaic's webhook to already be configured -
    // there's no separate mosaic-only webhook field, same as every other
    // notification type here.
    router.post('/mosaic/generate-now', async (req, res) => {
      try {
        const accountId = getAccountId(req) || 'default'
        const { getAccountMonthString, previousMonthString, resolveAccountTimezone } = require('../utils/dateUtils')
        const { generateAndPostMosaic } = require('../utils/posterMosaic')

        const acc = await prisma.appAccount.findUnique({ where: { id: accountId }, select: { sync: true } })
        let cfg = acc?.sync
        if (typeof cfg === 'string') { try { cfg = JSON.parse(cfg) } catch { cfg = {} } }
        cfg = cfg || {}
        if (!cfg.webhookUrl) {
          return res.status(400).json({ message: 'Set a Discord webhook URL first (Settings → Notifications)' })
        }

        const timeZone = await resolveAccountTimezone(prisma, accountId)
        const month = (typeof req.body?.month === 'string' && /^\d{4}-\d{2}$/.test(req.body.month))
          ? req.body.month
          : previousMonthString(getAccountMonthString(new Date(), timeZone))

        const result = await generateAndPostMosaic(prisma, accountId, cfg.webhookUrl, month, timeZone)
        return res.json(result)
      } catch (e) {
        return res.status(500).json({ message: e?.message || 'Failed to generate mosaic' })
      }
    })

    // DELETE /settings/backups/:filename
    router.delete('/backups/:filename', async (req, res) => {
      try {
        if (!isValidBackupFilename(req.params.filename)) {
          return res.status(400).json({ message: 'Invalid backup filename' })
        }
        const filePath = path.join(BACKUP_DIR, req.params.filename)
        if (!fs.existsSync(filePath)) return res.status(404).json({ message: 'Backup not found' })
        fs.unlinkSync(filePath)
        try {
          const validationFile = filePath.replace(/\.json$/, '.validation.json')
          if (fs.existsSync(validationFile)) fs.unlinkSync(validationFile)
        } catch {}
        return res.json({ success: true })
      } catch (e) {
        return res.status(500).json({ message: 'Failed to delete backup', error: e?.message })
      }
    })

    let backupTimer = null

    // Initialize backup schedule on startup
    scheduleBackups(readBackupFrequencyDays(), prisma)

    // Get backup frequency setting
    router.get('/backup-frequency', async (req, res) => {
      try {
        return res.json({ days: readBackupFrequencyDays() })
      } catch {
        return res.status(500).json({ message: 'Failed to read backup frequency' })
      }
    })

    // Update backup frequency setting
    router.put('/backup-frequency', async (req, res) => {
      try {
        const days = Number(req.body?.days || 0)
        if (!Number.isFinite(days) || days < 0) return res.status(400).json({ message: 'Invalid days' })
        writeBackupFrequencyDays(days)
        scheduleBackups(days, prisma)
        return res.json({ message: 'Backup frequency updated', days })
      } catch {
        return res.status(500).json({ message: 'Failed to update backup frequency' })
      }
    })

    // Manual backup trigger
    router.post('/backup-now', async (req, res) => {
      try {
        await performBackupOnce(prisma)
        return res.json({ message: 'Backup started' })
      } catch {
        return res.status(500).json({ message: 'Failed to start backup' })
      }
    })
  }

  // Backup frequency endpoints - available in all modes (public returns disabled)
  router.get('/backup-frequency', async (req, res) => {
    try {
      if (INSTANCE_TYPE === 'public') {
        // Backups are not supported in public mode
        return res.json({ days: 0 })
      }
      const { readBackupFrequencyDays } = require('../utils/backup')
      return res.json({ days: readBackupFrequencyDays() })
    } catch {
      return res.status(500).json({ message: 'Failed to read backup frequency' })
    }
  })

  router.put('/backup-frequency', async (req, res) => {
    try {
      if (INSTANCE_TYPE === 'public') {
        return res.status(403).json({ message: 'Backups are not available in public mode' })
      }
      const { writeBackupFrequencyDays, scheduleBackups } = require('../utils/backup')
      const days = Number(req.body?.days || 0)
      if (!Number.isFinite(days) || days < 0) return res.status(400).json({ message: 'Invalid days' })
      writeBackupFrequencyDays(days)
      scheduleBackups(days, prisma)
      return res.json({ message: 'Backup frequency updated', days })
    } catch {
      return res.status(500).json({ message: 'Failed to update backup frequency' })
    }
  })

  router.post('/backup-now', async (req, res) => {
    try {
      if (INSTANCE_TYPE === 'public') {
        return res.status(403).json({ message: 'Backups are not available in public mode' })
      }
      const { performBackupOnce } = require('../utils/backup')
      await performBackupOnce(prisma)
      return res.json({ message: 'Backup started' })
    } catch {
      return res.status(500).json({ message: 'Failed to start backup' })
    }
  })

  // Sync settings endpoints - available in all modes
  const {
    readSyncFrequencyMinutes,
    writeSyncFrequencyMinutes,
    scheduleSyncs
  } = require('../utils/syncScheduler');

  // Per-account sync settings (AUTH mode)
  router.get('/account-sync', async (req, res) => {
    try {
      if (INSTANCE_TYPE !== 'public') {
        const account = await ensureDefaultAccount()
        let syncCfg = account?.sync
        if (syncCfg && typeof syncCfg === 'string') {
          try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null }
        }

        const minutes = readSyncFrequencyMinutes()
        const derivedFrequency = minutes === 1 ? '1m' : (minutes >= 1440 ? `${Math.round(minutes / 1440)}d` : `${minutes}m`)

        const enabled = syncCfg && typeof syncCfg === 'object'
          ? syncCfg.enabled !== false
          : minutes > 0

        const response = {
          enabled,
          frequency: (syncCfg && typeof syncCfg === 'object' && syncCfg.frequency) ? String(syncCfg.frequency).trim() : derivedFrequency,
          safe: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.safe === 'boolean') ? syncCfg.safe : true,
          mode: (syncCfg && typeof syncCfg === 'object' && syncCfg.mode === 'advanced') ? 'advanced' : 'normal',
          webhookUrl: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.webhookUrl === 'string') ? syncCfg.webhookUrl : '',
          useCustomFields: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.useCustomFields === 'boolean') ? syncCfg.useCustomFields : ((syncCfg && typeof syncCfg === 'object' && typeof syncCfg.useCustomNames === 'boolean') ? syncCfg.useCustomNames : false),
          notifyOnActivity: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnActivity === true : false,
          notifyOnSync: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnSync === true : false,
          notifyOnInvite: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnInvite === true : false,
          notifyOnVault: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnVault === true : false,
          notifyOnAddonHealth: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnAddonHealth === true : false,
          notifyOnBackup: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnBackup === true : false,
          notifyOnMosaic: (syncCfg && typeof syncCfg === 'object') ? syncCfg.notifyOnMosaic === true : false,
          accountTimezone: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.accountTimezone === 'string' && syncCfg.accountTimezone.trim()) ? syncCfg.accountTimezone.trim() : DEFAULT_TIMEZONE,
          vaultCurrency: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.vaultCurrency === 'string' && syncCfg.vaultCurrency.trim()) ? syncCfg.vaultCurrency.trim() : 'USD',
          // SlickTrax features (v1.29-v1.30, named "Personal Features" pre-v1.37).
          // All default true so existing installs get the same behavior; a
          // user who explicitly turns any off (Settings → SlickTrax) hides
          // the corresponding UI.
          enableWatchlist: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.enableWatchlist === 'boolean') ? syncCfg.enableWatchlist : true,
          enableWatchedIndicators: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.enableWatchedIndicators === 'boolean') ? syncCfg.enableWatchedIndicators : true,
          enableRecommendations: (syncCfg && typeof syncCfg === 'object' && typeof syncCfg.enableRecommendations === 'boolean') ? syncCfg.enableRecommendations : true,
        }

        return res.json(response)
      }
      const acc = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { sync: true } })
      let syncCfg = acc?.sync || null
      if (syncCfg && typeof syncCfg === 'string') {
        try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null }
      }
      if (syncCfg && typeof syncCfg === 'object') {
        const safe = (typeof syncCfg.safe === 'boolean') ? syncCfg.safe : !syncCfg.unsafe
        const mode = syncCfg.mode === 'advanced' ? 'advanced' : 'normal'
        const frequency = (typeof syncCfg.frequency === 'string' && syncCfg.frequency.trim())
          ? syncCfg.frequency.trim()
          : '0'
        const resp = {
          enabled: syncCfg.enabled !== false, safe, mode, frequency, lastRunAt: syncCfg.lastRunAt,
          webhookUrl: syncCfg.webhookUrl || '',
          useCustomFields: (typeof syncCfg.useCustomFields === 'boolean') ? syncCfg.useCustomFields : ((typeof syncCfg.useCustomNames === 'boolean') ? syncCfg.useCustomNames : false),
          notifyOnActivity: syncCfg.notifyOnActivity === true,
          notifyOnSync: syncCfg.notifyOnSync === true,
          notifyOnInvite: syncCfg.notifyOnInvite === true,
          notifyOnVault: syncCfg.notifyOnVault === true,
          notifyOnAddonHealth: syncCfg.notifyOnAddonHealth === true,
          notifyOnBackup: syncCfg.notifyOnBackup === true,
          notifyOnMosaic: syncCfg.notifyOnMosaic === true,
          accountTimezone: (typeof syncCfg.accountTimezone === 'string' && syncCfg.accountTimezone.trim()) ? syncCfg.accountTimezone.trim() : DEFAULT_TIMEZONE,
          vaultCurrency: (typeof syncCfg.vaultCurrency === 'string' && syncCfg.vaultCurrency.trim()) ? syncCfg.vaultCurrency.trim() : 'USD',
          enableWatchlist: typeof syncCfg.enableWatchlist === 'boolean' ? syncCfg.enableWatchlist : true,
          enableWatchedIndicators: typeof syncCfg.enableWatchedIndicators === 'boolean' ? syncCfg.enableWatchedIndicators : true,
          enableRecommendations: typeof syncCfg.enableRecommendations === 'boolean' ? syncCfg.enableRecommendations : true,
        }
        return res.json(resp)
      }
      return res.json({ enabled: false, frequency: 0, safe: true, mode: 'normal', useCustomFields: false, notifyOnActivity: false, notifyOnSync: false, notifyOnInvite: false, notifyOnVault: false, notifyOnAddonHealth: false, notifyOnBackup: false, notifyOnMosaic: false, accountTimezone: DEFAULT_TIMEZONE, vaultCurrency: 'USD', enableWatchlist: true, enableWatchedIndicators: true, enableRecommendations: true })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to read account sync settings' })
    }
  })

  router.put('/account-sync', async (req, res) => {
    try {
      const { enabled, frequency, mode, unsafe, safe, webhookUrl, useCustomFields, useCustomNames, notifyOnActivity, notifyOnSync, notifyOnInvite, notifyOnVault, notifyOnAddonHealth, notifyOnBackup, notifyOnMosaic, accountTimezone, vaultCurrency, enableWatchlist, enableWatchedIndicators, enableRecommendations } = req.body || {}
      // Support both useCustomFields (new) and useCustomNames (old) for backward compatibility
      const useCustomFieldsValue = useCustomFields !== undefined ? useCustomFields : useCustomNames
      if (INSTANCE_TYPE !== 'public') {
        await ensureDefaultAccount()
        const safeMinutes = (() => {
          if (frequency === undefined || frequency === null) return null
          if (typeof frequency === 'number') return frequency
          if (typeof frequency === 'string') {
            const trimmed = frequency.trim().toLowerCase()
            if (trimmed.endsWith('d')) {
              const days = Number(trimmed.slice(0, -1))
              return Number.isFinite(days) && days > 0 ? days * 1440 : null
            }
            if (trimmed.endsWith('h')) {
              const hours = Number(trimmed.slice(0, -1))
              return Number.isFinite(hours) && hours > 0 ? hours * 60 : null
            }
            if (trimmed.endsWith('m')) {
              const mins = Number(trimmed.slice(0, -1))
              return Number.isFinite(mins) && mins >= 0 ? mins : null
            }
            const raw = Number(trimmed)
            return Number.isFinite(raw) && raw >= 0 ? raw : null
          }
          return null
        })()

        if (safeMinutes !== null && safeMinutes < 0) {
          return res.status(400).json({ message: 'Invalid frequency value' })
        }

        const nextMinutes = enabled === false ? 0 : (safeMinutes ?? readSyncFrequencyMinutes())
        if (!Number.isFinite(nextMinutes) || nextMinutes < 0) {
          return res.status(400).json({ message: 'Invalid minutes' })
        }

        writeSyncFrequencyMinutes(nextMinutes)

        const current = await prisma.appAccount.findUnique({ where: { id: DEFAULT_ACCOUNT_ID }, select: { sync: true } })
        let syncCfg = current?.sync
        if (syncCfg && typeof syncCfg === 'string') {
          try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null }
        }
        const baseCfg = (syncCfg && typeof syncCfg === 'object') ? syncCfg : {}
        const nextCfg = {
          ...baseCfg,
          enabled: enabled === undefined ? baseCfg.enabled !== false : !!enabled,
          frequency: typeof frequency === 'string' && frequency.trim() ? frequency.trim() : baseCfg.frequency || '0',
          safe: safe !== undefined ? !!safe : (unsafe !== undefined ? !unsafe : baseCfg.safe !== false),
          mode: mode === 'advanced' ? 'advanced' : baseCfg.mode === 'advanced' ? 'advanced' : 'normal',
          webhookUrl: webhookUrl !== undefined ? (webhookUrl || null) : (baseCfg.webhookUrl || null),
          useCustomFields: useCustomFieldsValue !== undefined ? !!useCustomFieldsValue : ((baseCfg.useCustomFields !== undefined ? baseCfg.useCustomFields : (baseCfg.useCustomNames !== undefined ? baseCfg.useCustomNames : false))),
          notifyOnActivity: notifyOnActivity !== undefined ? !!notifyOnActivity : ((baseCfg.notifyOnActivity !== undefined) ? baseCfg.notifyOnActivity : false),
          notifyOnSync: notifyOnSync !== undefined ? !!notifyOnSync : ((baseCfg.notifyOnSync !== undefined) ? baseCfg.notifyOnSync : false),
          notifyOnInvite: notifyOnInvite !== undefined ? !!notifyOnInvite : ((baseCfg.notifyOnInvite !== undefined) ? baseCfg.notifyOnInvite : false),
          notifyOnVault: notifyOnVault !== undefined ? !!notifyOnVault : ((baseCfg.notifyOnVault !== undefined) ? baseCfg.notifyOnVault : false),
          notifyOnAddonHealth: notifyOnAddonHealth !== undefined ? !!notifyOnAddonHealth : ((baseCfg.notifyOnAddonHealth !== undefined) ? baseCfg.notifyOnAddonHealth : false),
          notifyOnBackup: notifyOnBackup !== undefined ? !!notifyOnBackup : ((baseCfg.notifyOnBackup !== undefined) ? baseCfg.notifyOnBackup : false),
          notifyOnMosaic: notifyOnMosaic !== undefined ? !!notifyOnMosaic : ((baseCfg.notifyOnMosaic !== undefined) ? baseCfg.notifyOnMosaic : false),
          accountTimezone: typeof accountTimezone === 'string' && accountTimezone.trim() ? accountTimezone.trim() : (baseCfg.accountTimezone || DEFAULT_TIMEZONE),
          vaultCurrency: typeof vaultCurrency === 'string' && vaultCurrency.trim() ? vaultCurrency.trim().toUpperCase() : (baseCfg.vaultCurrency || 'USD'),
          enableWatchlist: enableWatchlist !== undefined ? !!enableWatchlist : (typeof baseCfg.enableWatchlist === 'boolean' ? baseCfg.enableWatchlist : true),
          enableWatchedIndicators: enableWatchedIndicators !== undefined ? !!enableWatchedIndicators : (typeof baseCfg.enableWatchedIndicators === 'boolean' ? baseCfg.enableWatchedIndicators : true),
          enableRecommendations: enableRecommendations !== undefined ? !!enableRecommendations : (typeof baseCfg.enableRecommendations === 'boolean' ? baseCfg.enableRecommendations : true),
        }

        try {
          await prisma.appAccount.update({ where: { id: DEFAULT_ACCOUNT_ID }, data: { sync: nextCfg } })
        } catch {
          await prisma.appAccount.update({ where: { id: DEFAULT_ACCOUNT_ID }, data: { sync: JSON.stringify(nextCfg) } })
        }

        const { reloadGroupAddons } = require('../routes/users')
        const scopedWhere = require('../utils/helpers').scopedWhere
        const decrypt = require('../utils/encryption').decrypt
        const schedulerReq = { appAccountId: DEFAULT_ACCOUNT_ID }
        scheduleSyncs(nextMinutes, prisma, getAccountId, scopedWhere, decrypt, reloadGroupAddons, schedulerReq, false)
        return res.json({ message: 'Sync settings updated' })
      }
      // Load current config to preserve unspecified fields
      const acc = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { sync: true } })
      let current = acc?.sync || null
      if (current && typeof current === 'string') { try { current = JSON.parse(current) } catch { current = null } }
      const base = (current && typeof current === 'object') ? current : {}

      // Build partial update only for provided fields
      const partial = {}
      if (enabled !== undefined) partial.enabled = !!enabled
      if (frequency !== undefined) partial.frequency = String(frequency)
      if (mode !== undefined) partial.mode = (mode === 'advanced') ? 'advanced' : 'normal'
      if (safe !== undefined) partial.safe = !!safe
      else if (unsafe !== undefined) partial.safe = !unsafe
      if (webhookUrl !== undefined) partial.webhookUrl = webhookUrl || null
      if (useCustomFieldsValue !== undefined) partial.useCustomFields = !!useCustomFieldsValue
      if (notifyOnActivity !== undefined) partial.notifyOnActivity = !!notifyOnActivity
      if (notifyOnSync !== undefined) partial.notifyOnSync = !!notifyOnSync
      if (notifyOnInvite !== undefined) partial.notifyOnInvite = !!notifyOnInvite
      if (notifyOnVault !== undefined) partial.notifyOnVault = !!notifyOnVault
      if (notifyOnAddonHealth !== undefined) partial.notifyOnAddonHealth = !!notifyOnAddonHealth
      if (notifyOnBackup !== undefined) partial.notifyOnBackup = !!notifyOnBackup
      if (notifyOnMosaic !== undefined) partial.notifyOnMosaic = !!notifyOnMosaic
      if (typeof accountTimezone === 'string' && accountTimezone.trim()) partial.accountTimezone = accountTimezone.trim()
      if (typeof vaultCurrency === 'string' && vaultCurrency.trim()) partial.vaultCurrency = vaultCurrency.trim().toUpperCase()
      if (enableWatchlist !== undefined) partial.enableWatchlist = !!enableWatchlist
      if (enableWatchedIndicators !== undefined) partial.enableWatchedIndicators = !!enableWatchedIndicators
      if (enableRecommendations !== undefined) partial.enableRecommendations = !!enableRecommendations

      const nextCfg = { ...base, ...partial }

      // Persist JSON (Postgres) or stringified (SQLite)
      try {
        await prisma.appAccount.update({ where: { id: req.appAccountId }, data: { sync: nextCfg } })
      } catch {
        await prisma.appAccount.update({ where: { id: req.appAccountId }, data: { sync: JSON.stringify(nextCfg) } })
      }
      // Reschedule heap with new config (scheduler will re-seed on next scheduleSyncs call)
      const { reloadGroupAddons } = require('../routes/users');
      const scopedWhere = require('../utils/helpers').scopedWhere;
      const decrypt = require('../utils/encryption').decrypt;
      scheduleSyncs(0, prisma, getAccountId, scopedWhere, decrypt, reloadGroupAddons, req, true) // clear
      scheduleSyncs(1, prisma, getAccountId, scopedWhere, decrypt, reloadGroupAddons, req, true) // re-seed; minutes ignored in AUTH mode
      return res.json({ message: 'Account sync settings updated' })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to update account sync settings', error: e?.message })
    }
  })

  // Theme preferences (account-scoped, so a theme choice made on one device
  // shows up on every other device signed into the same account). Stored on
  // AppAccount.sync.themePref — no schema migration needed. The shape is
  // deliberately loose (just JSON) so client-side additions (new fonts, extra
  // color overrides) don't require a server update.
  router.get('/theme-pref', async (req, res) => {
    try {
      const accountId = INSTANCE_TYPE === 'public' ? req.appAccountId : DEFAULT_ACCOUNT_ID
      if (!accountId) return res.status(401).json({ message: 'Unauthorized' })
      if (INSTANCE_TYPE !== 'public') await ensureDefaultAccount()
      const acc = await prisma.appAccount.findUnique({ where: { id: accountId }, select: { sync: true } })
      let syncCfg = acc?.sync
      if (typeof syncCfg === 'string') { try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null } }
      const themePref = (syncCfg && typeof syncCfg === 'object' && syncCfg.themePref && typeof syncCfg.themePref === 'object')
        ? syncCfg.themePref
        : null
      return res.json({ themePref })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to read theme preferences' })
    }
  })

  router.put('/theme-pref', async (req, res) => {
    try {
      const accountId = INSTANCE_TYPE === 'public' ? req.appAccountId : DEFAULT_ACCOUNT_ID
      if (!accountId) return res.status(401).json({ message: 'Unauthorized' })
      if (INSTANCE_TYPE !== 'public') await ensureDefaultAccount()
      const { themePref } = req.body || {}
      if (themePref !== null && (typeof themePref !== 'object' || Array.isArray(themePref))) {
        return res.status(400).json({ message: 'themePref must be an object or null' })
      }
      const acc = await prisma.appAccount.findUnique({ where: { id: accountId }, select: { sync: true } })
      let syncCfg = acc?.sync
      if (typeof syncCfg === 'string') { try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null } }
      if (!syncCfg || typeof syncCfg !== 'object') syncCfg = {}
      const nextCfg = { ...syncCfg, themePref: themePref || undefined }
      try { await prisma.appAccount.update({ where: { id: accountId }, data: { sync: nextCfg } }) }
      catch { await prisma.appAccount.update({ where: { id: accountId }, data: { sync: JSON.stringify(nextCfg) } }) }
      return res.json({ themePref })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to save theme preferences' })
    }
  })

  router.post('/account-sync/test-webhook', async (req, res) => {
    try {
      const providedUrl = typeof req.body?.webhookUrl === 'string' ? req.body.webhookUrl.trim() : ''
      let targetUrl = providedUrl

      const readAccountWebhook = async (accountId) => {
        const acc = await prisma.appAccount.findUnique({ where: { id: accountId }, select: { sync: true } })
        if (!acc) return null
        let syncCfg = acc.sync
        if (typeof syncCfg === 'string') {
          try { syncCfg = JSON.parse(syncCfg) } catch { syncCfg = null }
        }
        if (syncCfg && typeof syncCfg === 'object' && syncCfg.webhookUrl) {
          return String(syncCfg.webhookUrl)
        }
        return null
      }

      if (!targetUrl) {
        if (INSTANCE_TYPE === 'public') {
          if (!req.appAccountId) {
            return res.status(401).json({ message: 'Unauthorized' })
          }
          targetUrl = await readAccountWebhook(req.appAccountId)
        } else {
          await ensureDefaultAccount()
          targetUrl = await readAccountWebhook(DEFAULT_ACCOUNT_ID)
        }
      }

      if (!targetUrl) {
        return res.status(400).json({ message: 'No webhook URL configured' })
      }

      await postDiscord(targetUrl, '🔬 SlickSync test webhook message')
      return res.json({ message: 'Test message sent' })
    } catch (e) {
      console.error('Failed to send webhook test:', e)
      return res.status(500).json({ message: 'Failed to send test message', error: e?.message })
    }
  })

  // Manual sync trigger
  router.post('/sync-now', async (req, res) => {
    try {
      const { syncGroupUsers } = require('../routes/groups');
      const scopedWhere = require('../utils/helpers').scopedWhere;
      const decrypt = require('../utils/encryption').decrypt;

      const accountId = INSTANCE_TYPE === 'public' ? req.appAccountId : DEFAULT_ACCOUNT_ID;
      const syncReq = { appAccountId: accountId, headers: {}, body: {} };

      const groups = await prisma.group.findMany({
        where: scopedWhere(syncReq, {}),
        select: { id: true }
      });

      if (groups.length === 0) {
        return res.json({ message: 'No groups found to sync', syncedGroups: 0, failedGroups: 0, totalGroups: 0 });
      }

      let syncedGroups = 0;
      let failedGroups = 0;

      for (const group of groups) {
        try {
          const result = await syncGroupUsers(prisma, getAccountId, scopedWhere, decrypt, group.id, syncReq);
          if (result?.error) {
            failedGroups++;
          } else {
            syncedGroups++;
          }
        } catch (e) {
          failedGroups++;
        }
      }

      return res.json({
        message: 'Sync completed',
        syncedGroups,
        failedGroups,
        totalGroups: groups.length
      });
    } catch (e) {
      return res.status(500).json({ message: 'Failed to start sync', error: e?.message })
    }
  })

  // API Key management (generate/revoke)
  router.get('/account-api', async (req, res) => {
    try {
      const acc = await prisma.appAccount.findUnique({ where: { id: req.appAccountId }, select: { apiKeyHash: true } })
      if (!acc?.apiKeyHash) {
        return res.json({ hasKey: false, apiKey: null })
      }
      // Decrypt using account-specific key (accountId + server key)
      try {
        const { getServerKey, aesGcmDecrypt } = require('../utils/encryption')
        const serverKey = getServerKey()
        const accountKey = require('crypto').createHash('sha256').update(Buffer.concat([Buffer.from(req.appAccountId || ''), serverKey])).digest()
        const decrypted = aesGcmDecrypt(accountKey, acc.apiKeyHash)
        return res.json({ hasKey: true, apiKey: decrypted })
      } catch (e) {
        // If decryption fails, key might be in old format - treat as no key
        return res.json({ hasKey: false, apiKey: null })
      }
    } catch {
      return res.status(500).json({ message: 'Failed to read API key status' })
    }
  })

  router.post('/account-api-key', async (req, res) => {
    try {
      if (!req.appAccountId) {
        return res.status(401).json({ message: 'Unauthorized' })
      }
      const { generateApiKey } = require('../utils/apiKey')
      const { getServerKey, aesGcmEncrypt } = require('../utils/encryption')
      const key = generateApiKey()
      // Encrypt using account-specific key (accountId + server key)
      const serverKey = getServerKey()
      const accountKey = require('crypto').createHash('sha256').update(Buffer.concat([Buffer.from(req.appAccountId || ''), serverKey])).digest()
      const encrypted = aesGcmEncrypt(accountKey, key)
      await prisma.appAccount.update({ where: { id: req.appAccountId }, data: { apiKeyHash: encrypted } })
      // Return the full key ONCE
      return res.json({ apiKey: key })
    } catch (e) {
      console.error('Error generating API key:', e)
      return res.status(500).json({ message: 'Failed to generate API key', error: e?.message })
    }
  })

  router.delete('/account-api-key', async (req, res) => {
    try {
      await prisma.appAccount.update({ where: { id: req.appAccountId }, data: { apiKeyHash: null } })
      return res.json({ message: 'API key revoked' })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to revoke API key' })
    }
  })

  // Repair addons metadata (fill missing stremioAddonId and iconUrl from manifest)
  // Scopes to current account when AUTH is enabled
  router.post('/repair-addons', async (req, res) => {
    try {
      const whereScope = INSTANCE_TYPE === 'public' && req.appAccountId ? { accountId: req.appAccountId } : {}
      const addons = await prisma.addon.findMany({ where: whereScope })
      const { repairAddonsList } = require('../utils/repair')
      const result = await repairAddonsList({
        prisma,
        INSTANCE_TYPE,
        getAccountDek,
        getDecryptedManifestUrl,
        filterManifestByResources: require('../utils/stremio').filterManifestByResources,
        filterManifestByCatalogs: require('../utils/stremio').filterManifestByCatalogs,
        manifestHash: require('../utils/stremio').manifestHash,
        encrypt: require('../utils/encryption').encrypt
      }, req, addons)

      return res.json({ message: 'Repair completed', ...result })
    } catch (e) {
      return res.status(500).json({ message: 'Failed to repair addons', error: e?.message })
    }
  })

  // Addon health check settings endpoints
  const { 
    getHealthCheckIntervalMinutes,
    triggerManualHealthCheck 
  } = require('../utils/addonHealthCheck');

  // Get health check interval setting
  router.get('/addon-health-check', async (req, res) => {
    try {
      const intervalMinutes = getHealthCheckIntervalMinutes();
      return res.json({ 
        enabled: intervalMinutes >= 1,
        intervalMinutes 
      });
    } catch (e) {
      return res.status(500).json({ message: 'Failed to read health check settings' });
    }
  });

  // Update health check interval (requires restart to take effect)
  router.put('/addon-health-check', async (req, res) => {
    try {
      const { intervalMinutes } = req.body || {};
      
      if (intervalMinutes === undefined) {
        return res.status(400).json({ message: 'intervalMinutes is required' });
      }
      
      const parsed = parseInt(intervalMinutes, 10);
      if (isNaN(parsed) || parsed < 0) {
        return res.status(400).json({ message: 'Invalid intervalMinutes value' });
      }
      
      // Store in environment variable for now
      // In production, this would ideally be stored in the database
      process.env.ADDON_HEALTH_CHECK_INTERVAL_MINUTES = String(parsed);
      
      return res.json({ 
        message: 'Health check interval updated. Restart server to apply changes.',
        intervalMinutes: parsed,
        enabled: parsed >= 1
      });
    } catch (e) {
      return res.status(500).json({ message: 'Failed to update health check settings', error: e?.message });
    }
  });

  // Trigger manual health check
  router.post('/addon-health-check/now', async (req, res) => {
    try {
      // Run in background
      const accountId = INSTANCE_TYPE === 'public' ? req.appAccountId : DEFAULT_ACCOUNT_ID;
      triggerManualHealthCheck(prisma, accountId);
      
      return res.json({ message: 'Health check started' });
    } catch (e) {
      return res.status(500).json({ message: 'Failed to start health check', error: e?.message });
    }
  });

  return router;
};
