// Auto-generated themed catalogs (opt-in, Settings -> SlickTrax -> Auto-
// generated catalogs): detects a real taste cluster in the household's own
// watch history - a genre, or a genre+decade combo when one decade clearly
// dominates it - and turns it into an actual saved Catalog ("Your 90s
// Action Pack"), instead of a recommendation row that only ever scrolls by
// once. Candidate scoring mirrors /recommendations' own weighting
// (BASELINE_SECONDS floor + decayed real WatchActivity seconds) but is
// deliberately NOT shared code with discover.js - that endpoint also needs
// collaborative-boost/attribution/exclusion-set machinery this doesn't
// (a saved catalog isn't personalized to "you" the way a Discover row is,
// and it isn't excluding already-watched/watchlisted titles from the
// candidate pool - those ARE the taste signal here, not noise to filter).
//
// Regeneration keys off CustomList.autoGeneratedKey ("genre:X" or
// "genre:X|decade:Y"), so a later run refreshes the SAME catalog instead of
// duplicating it. A catalog the user deletes is recorded in
// DismissedThemedCatalog (see routes/lists.js's DELETE handler) so it never
// silently comes back on the next scan - same dismiss-persists-forever
// pattern as the duplicate-account merge suggestions in userMerge.js.

const BASELINE_SECONDS = 600 // same flat floor /recommendations uses for a real watch with no WatchActivity coverage
const HALF_LIFE_DAYS = 21
const ACTIVITY_LOOKBACK_DAYS = 90
const CANDIDATE_POOL = 40
const MAX_CLUSTERS = 2 // cap how many catalogs get (re)generated per account per run - a handful of strong clusters, not one per genre ever watched
const MIN_GENRE_SCORE = BASELINE_SECONDS * 4 // roughly "at least ~4 real watches" worth of weight before a genre counts as a cluster
const MIN_GENRE_ITEMS = 3 // need several distinct titles, not one binge-watched show carrying a genre alone
const ITEMS_PER_CATALOG = 20
const DECADE_DOMINANCE_RATIO = 0.6 // a decade must carry >=60% of the genre's weighted score to earn a decade-qualified name
const MIN_DECADE_ITEMS = 2

function parseYear(releaseInfo) {
  const match = /^(\d{4})/.exec(String(releaseInfo || ''))
  return match ? Number(match[1]) : null
}

/** Weighted candidate pool from real watch history, same shape /recommendations builds (see its own comment for why). */
async function buildScoredCandidates(prisma, accountId) {
  const lookbackDate = new Date(Date.now() - ACTIVITY_LOOKBACK_DAYS * 24 * 60 * 60 * 1000)
  const [movies, episodes, activity] = await Promise.all([
    prisma.movieWatchHistory.findMany({ where: { accountId }, select: { itemId: true, itemName: true }, distinct: ['itemId'] }),
    prisma.episodeWatchHistory.findMany({ where: { accountId }, select: { showId: true, showName: true }, distinct: ['showId'] }),
    prisma.watchActivity.findMany({ where: { accountId, date: { gte: lookbackDate } }, select: { itemId: true, itemType: true, watchTimeSeconds: true, date: true } }),
  ])

  const itemMeta = new Map()
  for (const m of movies) itemMeta.set(m.itemId, { name: m.itemName, type: 'movie' })
  for (const e of episodes) itemMeta.set(e.showId, { name: e.showName, type: 'series' })

  const scoreByItem = new Map()
  const now = Date.now()
  for (const a of activity) {
    if (!itemMeta.has(a.itemId)) continue
    const ageDays = (now - new Date(a.date).getTime()) / (24 * 60 * 60 * 1000)
    const decay = Math.pow(0.5, Math.max(0, ageDays) / HALF_LIFE_DAYS)
    scoreByItem.set(a.itemId, (scoreByItem.get(a.itemId) || 0) + a.watchTimeSeconds * decay)
  }
  for (const m of movies) if (!scoreByItem.has(m.itemId)) scoreByItem.set(m.itemId, BASELINE_SECONDS)
  for (const e of episodes) if (!scoreByItem.has(e.showId)) scoreByItem.set(e.showId, BASELINE_SECONDS)

  return [...scoreByItem.entries()]
    .map(([id, score]) => ({ id, score, ...itemMeta.get(id) }))
    .sort((a, b) => b.score - a.score)
    .slice(0, CANDIDATE_POOL)
}

/**
 * @param {Array<{id, score, type, genres: string[], releaseInfo: string|null}>} candidatesWithMeta
 * @returns {Array<{ key: string, label: string, type: 'movie'|'series', genre: string, decade: number|null, score: number }>}
 */
function detectClusters(candidatesWithMeta) {
  const genreScore = new Map()
  const genreItems = new Map()
  const genreByType = new Map()
  const genreDecadeScore = new Map()
  const genreDecadeItems = new Map()

  for (const c of candidatesWithMeta) {
    const decade = (() => { const y = parseYear(c.releaseInfo); return y ? Math.floor(y / 10) * 10 : null })()
    for (const genre of c.genres || []) {
      genreScore.set(genre, (genreScore.get(genre) || 0) + c.score)
      genreItems.set(genre, (genreItems.get(genre) || 0) + 1)
      if (!genreByType.has(genre)) genreByType.set(genre, new Map())
      const byType = genreByType.get(genre)
      byType.set(c.type, (byType.get(c.type) || 0) + c.score)
      if (decade !== null) {
        if (!genreDecadeScore.has(genre)) genreDecadeScore.set(genre, new Map())
        if (!genreDecadeItems.has(genre)) genreDecadeItems.set(genre, new Map())
        const dScore = genreDecadeScore.get(genre)
        const dItems = genreDecadeItems.get(genre)
        dScore.set(decade, (dScore.get(decade) || 0) + c.score)
        dItems.set(decade, (dItems.get(decade) || 0) + 1)
      }
    }
  }

  const clusters = []
  for (const [genre, score] of genreScore) {
    if (score < MIN_GENRE_SCORE || (genreItems.get(genre) || 0) < MIN_GENRE_ITEMS) continue

    const byType = genreByType.get(genre)
    const type = [...byType.entries()].sort((a, b) => b[1] - a[1])[0][0]

    let decade = null
    const dScore = genreDecadeScore.get(genre)
    const dItems = genreDecadeItems.get(genre)
    if (dScore && dScore.size > 0) {
      const [topDecade, topDecadeScore] = [...dScore.entries()].sort((a, b) => b[1] - a[1])[0]
      if (topDecadeScore / score >= DECADE_DOMINANCE_RATIO && (dItems.get(topDecade) || 0) >= MIN_DECADE_ITEMS) {
        decade = topDecade
      }
    }

    const key = decade !== null ? `genre:${genre}|decade:${decade}` : `genre:${genre}`
    const label = decade !== null ? `Your ${decade}s ${genre} Pack` : `Your ${genre} Favorites`
    clusters.push({ key, label, type, genre, decade, score })
  }

  return clusters.sort((a, b) => b.score - a.score).slice(0, MAX_CLUSTERS)
}

/** Real Cinemeta catalog items for a detected cluster, excluding anything already in the household's watch history. */
async function fetchClusterItems(cluster, excludeIds) {
  const { fetchCatalog } = require('./discover')
  let items = await fetchCatalog(cluster.type, { catalog: 'imdbRating', genre: cluster.genre })
  let filtered = items.filter((i) => !excludeIds.has(i.id))
  if (filtered.length < 6) {
    const popular = await fetchCatalog(cluster.type, { catalog: 'top', genre: cluster.genre })
    const seenIds = new Set(filtered.map((i) => i.id))
    for (const p of popular) {
      if (!excludeIds.has(p.id) && !seenIds.has(p.id)) filtered.push(p)
    }
  }
  if (cluster.decade !== null) {
    const decadeFiltered = filtered.filter((i) => {
      const year = parseYear(i.releaseInfo)
      return year !== null && year >= cluster.decade && year < cluster.decade + 10
    })
    // Only apply the decade filter if it leaves a real catalog - a thin
    // decade-restricted result is worse than the genre-wide fallback, and
    // the label already reads as an editorial pick, not a hard promise
    // every single item falls in that decade.
    if (decadeFiltered.length >= 6) filtered = decadeFiltered
  }
  return filtered.slice(0, ITEMS_PER_CATALOG).map((i) => ({
    id: i.id, type: i.type, name: i.name, poster: i.poster, year: parseYear(i.releaseInfo) || null,
  }))
}

async function isEnabledForAccount(prisma, accountId) {
  try {
    const acc = await prisma.appAccount.findUnique({ where: { id: accountId }, select: { sync: true } })
    let cfg = acc?.sync
    if (typeof cfg === 'string') { try { cfg = JSON.parse(cfg) } catch { cfg = null } }
    return !!(cfg && typeof cfg === 'object' && cfg.enableAutoThemedCatalogs === true)
  } catch { return false }
}

async function generateForAccount(prisma, accountId) {
  const { fetchMetadata } = require('./notify')
  const { resolveOmdbKeyForAccount } = require('./listImport')

  const candidates = await buildScoredCandidates(prisma, accountId)
  if (candidates.length === 0) return { created: 0, updated: 0 }

  const omdbApiKey = await resolveOmdbKeyForAccount(prisma, accountId).catch(() => null)
  const withGenres = await Promise.all(candidates.map(async (c) => {
    try {
      const meta = await fetchMetadata(c.id, c.type, null, omdbApiKey)
      return { ...c, genres: Array.isArray(meta?.genres) ? meta.genres : [], releaseInfo: meta?.releaseInfo || null }
    } catch { return { ...c, genres: [], releaseInfo: null } }
  }))

  const clusters = detectClusters(withGenres)
  if (clusters.length === 0) return { created: 0, updated: 0 }

  const dismissed = await prisma.dismissedThemedCatalog.findMany({ where: { accountId }, select: { key: true } })
  const dismissedKeys = new Set(dismissed.map((d) => d.key))
  const watchedIds = new Set(candidates.map((c) => c.id))

  let created = 0
  let updated = 0
  for (const cluster of clusters) {
    if (dismissedKeys.has(cluster.key)) continue
    const items = await fetchClusterItems(cluster, watchedIds)
    if (items.length === 0) continue

    const existing = await prisma.customList.findFirst({ where: { accountId, autoGeneratedKey: cluster.key } })
    if (existing) {
      await prisma.customList.update({ where: { id: existing.id }, data: { itemsJson: JSON.stringify(items) } })
      updated++
    } else {
      await prisma.customList.create({
        data: {
          accountId,
          name: cluster.label,
          description: 'Auto-generated from your watch history',
          itemsJson: JSON.stringify(items),
          autoGenerated: true,
          autoGeneratedKey: cluster.key,
        },
      })
      created++
    }
  }
  return { created, updated }
}

async function runAutoThemedCatalogs(prisma) {
  try {
    const accounts = await prisma.appAccount.findMany({ select: { id: true } })
    let totalCreated = 0
    let totalUpdated = 0
    let ranFor = 0
    for (const { id: accountId } of accounts) {
      if (!(await isEnabledForAccount(prisma, accountId))) continue
      ranFor++
      try {
        const { created, updated } = await generateForAccount(prisma, accountId)
        totalCreated += created
        totalUpdated += updated
      } catch (err) {
        console.warn(`[AutoThemedCatalogs] Failed for account ${accountId}:`, err?.message || err)
      }
    }
    if (ranFor > 0) console.log(`[AutoThemedCatalogs] ${totalCreated} created, ${totalUpdated} updated across ${ranFor} account(s)`)
  } catch (err) {
    console.warn('[AutoThemedCatalogs] Run failed:', err?.message || err)
  }
}

let timer = null
const INTERVAL_HOURS = 24

function scheduleAutoThemedCatalogs(prisma) {
  if (timer) {
    clearInterval(timer)
    timer = null
  }
  const intervalMs = INTERVAL_HOURS * 60 * 60 * 1000
  // Staggered well past the other boot-time schedulers.
  setTimeout(() => runAutoThemedCatalogs(prisma), 150 * 1000)
  timer = setInterval(() => runAutoThemedCatalogs(prisma), intervalMs)
  console.log(`[AutoThemedCatalogs] Scheduled every ${INTERVAL_HOURS}h`)
}

module.exports = {
  scheduleAutoThemedCatalogs,
  runAutoThemedCatalogs,
  generateForAccount,
  detectClusters,
  parseYear,
  isEnabledForAccount,
}
